// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "antrea.io/antrea/v2/pkg/apis/crd/v1alpha2"
	crdv1alpha2 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/crd/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPools implements IPPoolInterface
type fakeIPPools struct {
	*gentype.FakeClientWithList[*v1alpha2.IPPool, *v1alpha2.IPPoolList]
	Fake *FakeCrdV1alpha2
}

func newFakeIPPools(fake *FakeCrdV1alpha2) crdv1alpha2.IPPoolInterface {
	_ = "STUB: not implemented"
	return *new(crdv1alpha2.IPPoolInterface)
}
