// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/controller/networkpolicy (interfaces: EndpointQuerier,PolicyRuleQuerier)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/controller/networkpolicy/testing/mock_networkpolicy.go -package testing antrea.io/antrea/v2/pkg/controller/networkpolicy EndpointQuerier,PolicyRuleQuerier
//

// Package testing is a generated GoMock package.
package testing

import (
	controlplane "antrea.io/antrea/v2/pkg/apis/controlplane"
	types "antrea.io/antrea/v2/pkg/controller/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEndpointQuerier is a mock of EndpointQuerier interface.
type MockEndpointQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointQuerierMockRecorder
	isgomock struct{}
}

// MockEndpointQuerierMockRecorder is the mock recorder for MockEndpointQuerier.
type MockEndpointQuerierMockRecorder struct {
	mock *MockEndpointQuerier
}

// NewMockEndpointQuerier creates a new mock instance.
func NewMockEndpointQuerier(ctrl *gomock.Controller) *MockEndpointQuerier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointQuerier) EXPECT() *MockEndpointQuerierMockRecorder {
	_ = "STUB: not implemented"

	// QueryNetworkPolicyRules mocks base method.
	return nil
}

func (m *MockEndpointQuerier) QueryNetworkPolicyRules(namespace, podName string) (*types.EndpointNetworkPolicyRules, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryNetworkPolicyRules indicates an expected call of QueryNetworkPolicyRules.
func (mr *MockEndpointQuerierMockRecorder) QueryNetworkPolicyRules(namespace, podName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPolicyRuleQuerier is a mock of PolicyRuleQuerier interface.
type MockPolicyRuleQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyRuleQuerierMockRecorder
	isgomock struct{}
}

// MockPolicyRuleQuerierMockRecorder is the mock recorder for MockPolicyRuleQuerier.
type MockPolicyRuleQuerierMockRecorder struct {
	mock *MockPolicyRuleQuerier
}

// NewMockPolicyRuleQuerier creates a new mock instance.
func NewMockPolicyRuleQuerier(ctrl *gomock.Controller) *MockPolicyRuleQuerier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyRuleQuerier) EXPECT() *MockPolicyRuleQuerierMockRecorder {
	_ = "STUB: not implemented"

	// QueryNetworkPolicyEvaluation mocks base method.
	return nil
}

func (m *MockPolicyRuleQuerier) QueryNetworkPolicyEvaluation(entities *controlplane.NetworkPolicyEvaluationRequest) (*controlplane.NetworkPolicyEvaluationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryNetworkPolicyEvaluation indicates an expected call of QueryNetworkPolicyEvaluation.
func (mr *MockPolicyRuleQuerierMockRecorder) QueryNetworkPolicyEvaluation(entities any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
