// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
)

type CrdV1alpha1Interface interface {
	RESTClient() rest.Interface
	AntreaNodeConfigsGetter
	BGPPoliciesGetter
	ExternalNodesGetter
	FlowExporterDestinationsGetter
	NodeLatencyMonitorsGetter
	PacketCapturesGetter
	SupportBundleCollectionsGetter
}

// CrdV1alpha1Client is used to interact with features provided by the crd.antrea.io group.
type CrdV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CrdV1alpha1Client) AntreaNodeConfigs() AntreaNodeConfigInterface {
	_ = "STUB: not implemented"
	return *new(AntreaNodeConfigInterface)
}

func (c *CrdV1alpha1Client) BGPPolicies() BGPPolicyInterface {
	_ = "STUB: not implemented"
	return *new(BGPPolicyInterface)
}

func (c *CrdV1alpha1Client) ExternalNodes(namespace string) ExternalNodeInterface {
	_ = "STUB: not implemented"
	return *new(ExternalNodeInterface)
}

func (c *CrdV1alpha1Client) FlowExporterDestinations() FlowExporterDestinationInterface {
	_ = "STUB: not implemented"
	return *new(FlowExporterDestinationInterface)
}

func (c *CrdV1alpha1Client) NodeLatencyMonitors() NodeLatencyMonitorInterface {
	_ = "STUB: not implemented"
	return *new(NodeLatencyMonitorInterface)
}

func (c *CrdV1alpha1Client) PacketCaptures() PacketCaptureInterface {
	_ = "STUB: not implemented"
	return *new(PacketCaptureInterface)
}

func (c *CrdV1alpha1Client) SupportBundleCollections() SupportBundleCollectionInterface {
	_ = "STUB: not implemented"
	return *new(SupportBundleCollectionInterface)
}

// NewForConfig creates a new CrdV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*CrdV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new CrdV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*CrdV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new CrdV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CrdV1alpha1Client { _ = "STUB: not implemented"; return nil }

// New creates a new CrdV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CrdV1alpha1Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) { _ = "STUB: not implemented"; return }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CrdV1alpha1Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
