// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/util/ipset (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/util/ipset/testing/mock_ipset.go -package testing antrea.io/antrea/v2/pkg/agent/util/ipset Interface
//

// Package testing is a generated GoMock package.
package testing

import (
	ipset "antrea.io/antrea/v2/pkg/agent/util/ipset"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// AddEntry mocks base method.
	return nil
}

func (m *MockInterface) AddEntry(name, entry string) error { _ = "STUB: not implemented"; return nil }

// AddEntry indicates an expected call of AddEntry.
func (mr *MockInterfaceMockRecorder) AddEntry(name, entry any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateIPSet mocks base method.
func (m *MockInterface) CreateIPSet(name string, setType ipset.SetType, isIPv6 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateIPSet indicates an expected call of CreateIPSet.
func (mr *MockInterfaceMockRecorder) CreateIPSet(name, setType, isIPv6 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DelEntry mocks base method.
func (m *MockInterface) DelEntry(name, entry string) error { _ = "STUB: not implemented"; return nil }

// DelEntry indicates an expected call of DelEntry.
func (mr *MockInterfaceMockRecorder) DelEntry(name, entry any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DestroyIPSet mocks base method.
func (m *MockInterface) DestroyIPSet(name string) error { _ = "STUB: not implemented"; return nil }

// DestroyIPSet indicates an expected call of DestroyIPSet.
func (mr *MockInterfaceMockRecorder) DestroyIPSet(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListEntries mocks base method.
func (m *MockInterface) ListEntries(name string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockInterfaceMockRecorder) ListEntries(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Save mocks base method.
func (m *MockInterface) Save() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// Save indicates an expected call of Save.
func (mr *MockInterfaceMockRecorder) Save() *gomock.Call { _ = "STUB: not implemented"; return nil }
