// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package multicluster

import (
	"strings"

	"github.com/spf13/cobra"
	v1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"antrea.io/antrea/v2/pkg/antctl/raw/multicluster/common"
)

var joinOpts *joinOptions

type joinOptions struct {
	common.ClusterSetJoinConfig
	ConfigFile string
	Secret     *v1.Secret
	k8sClient  client.Client
}

func (o *joinOptions) validateAndComplete(cmd *cobra.Command) error {
	_ = "STUB: not implemented"
	return nil
}

// Try reading the Secret manifest from the config file.

// The precedence order is that TokenSecretName > TokenSecretFile > JoinConfigFile.

// Always set the Secret Namespace with the member cluster Multi-cluster Namespace.

func yamlUnmarshall(raw []byte, v interface{}) error { _ = "STUB: not implemented"; return nil }

func unmarshallSecret(raw []byte) (*v1.Secret, error) { _ = "STUB: not implemented"; return nil, nil }

// We may need to skip the first object, which can be comments and the
// starting "---" before the Secret.

var joinExamples = strings.Trim(`
# Join a ClusterSet with a pre-created token Secret
  $ antctl mc join --clusterset=clusterset1 \
                   --clusterid=cluster-east \
                   --leader-clusterid=cluster-north \
                   --leader-namespace=antrea-multicluster \
                   --leader-apiserver=https://172.18.0.3:6443 \
                   --token-secret-name=cluster-east-token \
                   --n kube-system

# Join a ClusterSet with a token Secret manifest
  $ antctl mc join --clusterset=clusterset1 \
                   --clusterid=cluster-east \
                   --leader-clusterid=cluster-north \
                   --leader-namespace=antrea-multicluster \
                   --leader-apiserver=https://172.18.0.3:6443 \
                   --token-secret-file=cluster-east-token.yml \
                   --n kube-system

# Join a ClusterSet with parameters defined in a config file
  $ antctl mc join --config-file join-config.yml

# Config file example:
---
apiVersion: multicluster.antrea.io/v1alpha1
kind: ClusterSetJoinConfig
clusterSetID: clusterset1
clusterID: cluster-east
namespace: kube-system
leaderClusterID: cluster-north
leaderNamespace: antrea-multicluster
leaderAPIServer: https://172.18.0.3:6443
# Use the pre-created token Secret.
#tokenSecretName: ""
# Create a token Secret with the manifest file.
#tokenSecretFile: ""
# Manifest to create a Secret for a member cluster token.
---
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
data:
# Generated by "init" or "create membertoken" command
  ca.crt: ...
  namespace: ...
  token: ...
type: Opaque
`, "\n")

func NewJoinCommand() *cobra.Command { _ = "STUB: not implemented"; return nil }

func joinRunE(cmd *cobra.Command, args []string) error { _ = "STUB: not implemented"; return nil }

func waitForMemberClusterReady(cmd *cobra.Command, k8sClient client.Client) error {
	_ = "STUB: not implemented"
	return nil
}

func waitForClusterSetReady(client client.Client, name string, namespace string, clusterID string) error {
	_ = "STUB: not implemented"
	return nil
}
