// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/ipfix (interfaces: IPFIXExportingProcess,IPFIXBufferedExporter,IPFIXRegistry)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/ipfix/testing/mock_ipfix.go -package testing antrea.io/antrea/v2/pkg/ipfix IPFIXExportingProcess,IPFIXBufferedExporter,IPFIXRegistry
//

// Package testing is a generated GoMock package.
package testing

import (
	entities "github.com/vmware/go-ipfix/pkg/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIPFIXExportingProcess is a mock of IPFIXExportingProcess interface.
type MockIPFIXExportingProcess struct {
	ctrl     *gomock.Controller
	recorder *MockIPFIXExportingProcessMockRecorder
	isgomock struct{}
}

// MockIPFIXExportingProcessMockRecorder is the mock recorder for MockIPFIXExportingProcess.
type MockIPFIXExportingProcessMockRecorder struct {
	mock *MockIPFIXExportingProcess
}

// NewMockIPFIXExportingProcess creates a new mock instance.
func NewMockIPFIXExportingProcess(ctrl *gomock.Controller) *MockIPFIXExportingProcess {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFIXExportingProcess) EXPECT() *MockIPFIXExportingProcessMockRecorder {
	_ = "STUB: not implemented"

	// CloseConnToCollector mocks base method.
	return nil
}

func (m *MockIPFIXExportingProcess) CloseConnToCollector() { _ = "STUB: not implemented"; return }

// CloseConnToCollector indicates an expected call of CloseConnToCollector.
func (mr *MockIPFIXExportingProcessMockRecorder) CloseConnToCollector() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewTemplateID mocks base method.
func (m *MockIPFIXExportingProcess) NewTemplateID() uint16 { _ = "STUB: not implemented"; return 0 }

// NewTemplateID indicates an expected call of NewTemplateID.
func (mr *MockIPFIXExportingProcessMockRecorder) NewTemplateID() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendSet mocks base method.
func (m *MockIPFIXExportingProcess) SendSet(set entities.Set) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// SendSet indicates an expected call of SendSet.
func (mr *MockIPFIXExportingProcessMockRecorder) SendSet(set any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockIPFIXBufferedExporter is a mock of IPFIXBufferedExporter interface.
type MockIPFIXBufferedExporter struct {
	ctrl     *gomock.Controller
	recorder *MockIPFIXBufferedExporterMockRecorder
	isgomock struct{}
}

// MockIPFIXBufferedExporterMockRecorder is the mock recorder for MockIPFIXBufferedExporter.
type MockIPFIXBufferedExporterMockRecorder struct {
	mock *MockIPFIXBufferedExporter
}

// NewMockIPFIXBufferedExporter creates a new mock instance.
func NewMockIPFIXBufferedExporter(ctrl *gomock.Controller) *MockIPFIXBufferedExporter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFIXBufferedExporter) EXPECT() *MockIPFIXBufferedExporterMockRecorder {
	_ = "STUB: not implemented"

	// AddRecord mocks base method.
	return nil
}

func (m *MockIPFIXBufferedExporter) AddRecord(record entities.Record) error {
	_ = "STUB: not implemented"
	return nil
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockIPFIXBufferedExporterMockRecorder) AddRecord(record any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Flush mocks base method.
func (m *MockIPFIXBufferedExporter) Flush() error { _ = "STUB: not implemented"; return nil }

// Flush indicates an expected call of Flush.
func (mr *MockIPFIXBufferedExporterMockRecorder) Flush() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockIPFIXRegistry is a mock of IPFIXRegistry interface.
type MockIPFIXRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockIPFIXRegistryMockRecorder
	isgomock struct{}
}

// MockIPFIXRegistryMockRecorder is the mock recorder for MockIPFIXRegistry.
type MockIPFIXRegistryMockRecorder struct {
	mock *MockIPFIXRegistry
}

// NewMockIPFIXRegistry creates a new mock instance.
func NewMockIPFIXRegistry(ctrl *gomock.Controller) *MockIPFIXRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFIXRegistry) EXPECT() *MockIPFIXRegistryMockRecorder {
	_ = "STUB: not implemented"

	// GetInfoElement mocks base method.
	return nil
}

func (m *MockIPFIXRegistry) GetInfoElement(name string, enterpriseID uint32) (*entities.InfoElement, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInfoElement indicates an expected call of GetInfoElement.
func (mr *MockIPFIXRegistryMockRecorder) GetInfoElement(name, enterpriseID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadRegistry mocks base method.
func (m *MockIPFIXRegistry) LoadRegistry() { _ = "STUB: not implemented"; return }

// LoadRegistry indicates an expected call of LoadRegistry.
func (mr *MockIPFIXRegistryMockRecorder) LoadRegistry() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
