// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
)

type CrdV1beta1Interface interface {
	RESTClient() rest.Interface
	AntreaAgentInfosGetter
	AntreaControllerInfosGetter
	ClusterGroupsGetter
	ClusterNetworkPoliciesGetter
	EgressesGetter
	ExternalIPPoolsGetter
	GroupsGetter
	IPPoolsGetter
	NetworkPoliciesGetter
	TiersGetter
	TraceflowsGetter
}

// CrdV1beta1Client is used to interact with features provided by the crd.antrea.io group.
type CrdV1beta1Client struct {
	restClient rest.Interface
}

func (c *CrdV1beta1Client) AntreaAgentInfos() AntreaAgentInfoInterface {
	_ = "STUB: not implemented"
	return *new(AntreaAgentInfoInterface)
}

func (c *CrdV1beta1Client) AntreaControllerInfos() AntreaControllerInfoInterface {
	_ = "STUB: not implemented"
	return *new(AntreaControllerInfoInterface)
}

func (c *CrdV1beta1Client) ClusterGroups() ClusterGroupInterface {
	_ = "STUB: not implemented"
	return *new(ClusterGroupInterface)
}

func (c *CrdV1beta1Client) ClusterNetworkPolicies() ClusterNetworkPolicyInterface {
	_ = "STUB: not implemented"
	return *new(ClusterNetworkPolicyInterface)
}

func (c *CrdV1beta1Client) Egresses() EgressInterface {
	_ = "STUB: not implemented"
	return *new(EgressInterface)
}

func (c *CrdV1beta1Client) ExternalIPPools() ExternalIPPoolInterface {
	_ = "STUB: not implemented"
	return *new(ExternalIPPoolInterface)
}

func (c *CrdV1beta1Client) Groups(namespace string) GroupInterface {
	_ = "STUB: not implemented"
	return *new(GroupInterface)
}

func (c *CrdV1beta1Client) IPPools() IPPoolInterface {
	_ = "STUB: not implemented"
	return *new(IPPoolInterface)
}

func (c *CrdV1beta1Client) NetworkPolicies(namespace string) NetworkPolicyInterface {
	_ = "STUB: not implemented"
	return *new(NetworkPolicyInterface)
}

func (c *CrdV1beta1Client) Tiers() TierInterface {
	_ = "STUB: not implemented"
	return *new(TierInterface)
}

func (c *CrdV1beta1Client) Traceflows() TraceflowInterface {
	_ = "STUB: not implemented"
	return *

	// NewForConfig creates a new CrdV1beta1Client for the given config.
	// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
	// where httpClient was generated with rest.HTTPClientFor(c).
	new(TraceflowInterface)
}

func NewForConfig(c *rest.Config) (*CrdV1beta1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new CrdV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*CrdV1beta1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new CrdV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CrdV1beta1Client { _ = "STUB: not implemented"; return nil }

// New creates a new CrdV1beta1Client for the given RESTClient.
func New(c rest.Interface) *CrdV1beta1Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) { _ = "STUB: not implemented"; return }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CrdV1beta1Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
