// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/monitortool (interfaces: PacketListener)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/monitortool/testing/mock_monitortool.go -package testing antrea.io/antrea/v2/pkg/agent/monitortool PacketListener
//

// Package testing is a generated GoMock package.
package testing

import (
	net "net"

	gomock "go.uber.org/mock/gomock"
)

// MockPacketListener is a mock of PacketListener interface.
type MockPacketListener struct {
	ctrl     *gomock.Controller
	recorder *MockPacketListenerMockRecorder
	isgomock struct{}
}

// MockPacketListenerMockRecorder is the mock recorder for MockPacketListener.
type MockPacketListenerMockRecorder struct {
	mock *MockPacketListener
}

// NewMockPacketListener creates a new mock instance.
func NewMockPacketListener(ctrl *gomock.Controller) *MockPacketListener {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketListener) EXPECT() *MockPacketListenerMockRecorder {
	_ = "STUB: not implemented"

	// ListenPacket mocks base method.
	return nil
}

func (m *MockPacketListener) ListenPacket(network, address string) (net.PacketConn, error) {
	_ = "STUB: not implemented"
	return *new(net.PacketConn), nil
}

// ListenPacket indicates an expected call of ListenPacket.
func (mr *MockPacketListenerMockRecorder) ListenPacket(network, address any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
