// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package clusteridentity

import (
	"time"

	"github.com/google/uuid"
	clientset "k8s.io/client-go/kubernetes"
)

const (
	DefaultClusterIdentityConfigMapName = "antrea-cluster-identity"
	uuidConfigMapKey                    = "uuid"
)

// ClusterIdentityAllocator ensures that the antrea-cluster-identity ConfigMap is populated
// correctly, with a valid UUID. It is meant to be used by the Antrea Controller.
type ClusterIdentityAllocator struct {
	clusterIdentityConfigMapNamespace string
	clusterIdentityConfigMapName      string
	k8sClient                         clientset.Interface
}

// NewClusterIdentityAllocator creates a ClusterIdentityAllocator object
func NewClusterIdentityAllocator(
	clusterIdentityConfigMapNamespace string,
	clusterIdentityConfigMapName string,
	k8sClient clientset.Interface,
) *ClusterIdentityAllocator {
	_ = "STUB: not implemented"
	return nil
}

func (a *ClusterIdentityAllocator) updateConfigMapIfNeeded() error {
	_ = "STUB: not implemented"
	return nil
}

// Run will ensure that the antrea-cluster-identity ConfigMap is up-to-date. It is meant to be
// called asynchronously in its own goroutine, and will keep retrying in case of error, using an
// exponential backoff mechanism.
func (a *ClusterIdentityAllocator) Run(stopCh <-chan struct{}) {
	_ = "STUB: not implemented"
	// Exponential backoff, starting at 100ms with a factor of 2. A "steps" value of 8 means we
	// will increase the backoff duration at most 8 times, so the max duration is (100ms * //
	// 2^8), which is about 25s.
	return
}

type ClusterIdentity struct {
	UUID uuid.UUID
}

// ClusterIdentityProvider is an interface used to retrieve the cluster identity information (UUID),
// as provided by the user or generated by the Antrea Controller. It also returns the time at which
// the antrea-cluster-identity was created, which can typically be considered as the time at which
// Antrea was deployed to the cluster.
type ClusterIdentityProvider interface {
	Get() (ClusterIdentity, time.Time, error)
}

type clusterIdentityProvider struct {
	clusterIdentityConfigMapNamespace string
	clusterIdentityConfigMapName      string
	k8sClient                         clientset.Interface
}

// NewClusterIdentityProvider returns a new object implementing the ClusterIdentityProvider
// interface.
func NewClusterIdentityProvider(
	clusterIdentityConfigMapNamespace string,
	clusterIdentityConfigMapName string,
	k8sClient clientset.Interface,
) *clusterIdentityProvider {
	_ = "STUB: not implemented"
	return nil
}

// Get will retrieve the cluster identity (UUID) stored in the antrea-cluster-identity ConfigMap. In
// case of error, clients are invited to retry as the information may not be available yet.
func (p *clusterIdentityProvider) Get() (ClusterIdentity, time.Time, error) {
	_ = "STUB: not implemented"
	return *new(ClusterIdentity), *new(time.Time), nil
}
