// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/ovs/ovsconfig (interfaces: OVSBridgeClient)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/ovs/ovsconfig/testing/mock_ovsconfig.go -package testing antrea.io/antrea/v2/pkg/ovs/ovsconfig OVSBridgeClient
//

// Package testing is a generated GoMock package.
package testing

import (
	net "net"
	time "time"

	ovsconfig "antrea.io/antrea/v2/pkg/ovs/ovsconfig"
	gomock "go.uber.org/mock/gomock"
)

// MockOVSBridgeClient is a mock of OVSBridgeClient interface.
type MockOVSBridgeClient struct {
	ctrl     *gomock.Controller
	recorder *MockOVSBridgeClientMockRecorder
	isgomock struct{}
}

// MockOVSBridgeClientMockRecorder is the mock recorder for MockOVSBridgeClient.
type MockOVSBridgeClientMockRecorder struct {
	mock *MockOVSBridgeClient
}

// NewMockOVSBridgeClient creates a new mock instance.
func NewMockOVSBridgeClient(ctrl *gomock.Controller) *MockOVSBridgeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOVSBridgeClient) EXPECT() *MockOVSBridgeClientMockRecorder {
	_ = "STUB: not implemented"

	// AddBridgeOtherConfig mocks base method.
	return nil
}

func (m *MockOVSBridgeClient) AddBridgeOtherConfig(configs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// AddBridgeOtherConfig indicates an expected call of AddBridgeOtherConfig.
func (mr *MockOVSBridgeClientMockRecorder) AddBridgeOtherConfig(configs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddOVSOtherConfig mocks base method.
func (m *MockOVSBridgeClient) AddOVSOtherConfig(configs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// AddOVSOtherConfig indicates an expected call of AddOVSOtherConfig.
func (mr *MockOVSBridgeClientMockRecorder) AddOVSOtherConfig(configs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockOVSBridgeClient) Create() ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// Create indicates an expected call of Create.
func (mr *MockOVSBridgeClientMockRecorder) Create() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateAccessPort mocks base method.
func (m *MockOVSBridgeClient) CreateAccessPort(name, ifDev string, externalIDs map[string]any, vlanID uint16) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreateAccessPort indicates an expected call of CreateAccessPort.
func (mr *MockOVSBridgeClientMockRecorder) CreateAccessPort(name, ifDev, externalIDs, vlanID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateInternalPort mocks base method.
func (m *MockOVSBridgeClient) CreateInternalPort(name string, ofPortRequest int32, mac string, externalIDs map[string]any) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreateInternalPort indicates an expected call of CreateInternalPort.
func (mr *MockOVSBridgeClientMockRecorder) CreateInternalPort(name, ofPortRequest, mac, externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePort mocks base method.
func (m *MockOVSBridgeClient) CreatePort(name, ifDev string, externalIDs map[string]any) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreatePort indicates an expected call of CreatePort.
func (mr *MockOVSBridgeClientMockRecorder) CreatePort(name, ifDev, externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateTunnelPort mocks base method.
func (m *MockOVSBridgeClient) CreateTunnelPort(name string, tunnelType ovsconfig.TunnelType, ofPortRequest int32) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreateTunnelPort indicates an expected call of CreateTunnelPort.
func (mr *MockOVSBridgeClientMockRecorder) CreateTunnelPort(name, tunnelType, ofPortRequest any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateTunnelPortExt mocks base method.
func (m *MockOVSBridgeClient) CreateTunnelPortExt(name string, tunnelType ovsconfig.TunnelType, ofPortRequest int32, csum bool, localIP, remoteIP, remoteName, psk string, extraOptions, externalIDs map[string]any) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreateTunnelPortExt indicates an expected call of CreateTunnelPortExt.
func (mr *MockOVSBridgeClientMockRecorder) CreateTunnelPortExt(name, tunnelType, ofPortRequest, csum, localIP, remoteIP, remoteName, psk, extraOptions, externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUplinkPort mocks base method.
func (m *MockOVSBridgeClient) CreateUplinkPort(name string, ofPortRequest int32, externalIDs map[string]any) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// CreateUplinkPort indicates an expected call of CreateUplinkPort.
func (mr *MockOVSBridgeClientMockRecorder) CreateUplinkPort(name, ofPortRequest, externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockOVSBridgeClient) Delete() ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// Delete indicates an expected call of Delete.
func (mr *MockOVSBridgeClientMockRecorder) Delete() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteOVSOtherConfig mocks base method.
func (m *MockOVSBridgeClient) DeleteOVSOtherConfig(configs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// DeleteOVSOtherConfig indicates an expected call of DeleteOVSOtherConfig.
func (mr *MockOVSBridgeClientMockRecorder) DeleteOVSOtherConfig(configs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeletePort mocks base method.
func (m *MockOVSBridgeClient) DeletePort(portUUID string) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// DeletePort indicates an expected call of DeletePort.
func (mr *MockOVSBridgeClientMockRecorder) DeletePort(portUUID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeletePorts mocks base method.
func (m *MockOVSBridgeClient) DeletePorts(portUUIDList []string) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// DeletePorts indicates an expected call of DeletePorts.
func (mr *MockOVSBridgeClientMockRecorder) DeletePorts(portUUIDList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBridgeName mocks base method.
func (m *MockOVSBridgeClient) GetBridgeName() string { _ = "STUB: not implemented"; return "" }

// GetBridgeName indicates an expected call of GetBridgeName.
func (mr *MockOVSBridgeClientMockRecorder) GetBridgeName() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDatapathID mocks base method.
func (m *MockOVSBridgeClient) GetDatapathID() (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// GetDatapathID indicates an expected call of GetDatapathID.
func (mr *MockOVSBridgeClientMockRecorder) GetDatapathID() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetExternalIDs mocks base method.
func (m *MockOVSBridgeClient) GetExternalIDs() (map[string]string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetExternalIDs indicates an expected call of GetExternalIDs.
func (mr *MockOVSBridgeClientMockRecorder) GetExternalIDs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceOptions mocks base method.
func (m *MockOVSBridgeClient) GetInterfaceOptions(name string) (map[string]string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetInterfaceOptions indicates an expected call of GetInterfaceOptions.
func (mr *MockOVSBridgeClientMockRecorder) GetInterfaceOptions(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOFPort mocks base method.
func (m *MockOVSBridgeClient) GetOFPort(ifName string, waitUntilValid bool) (int32, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return 0, *new(ovsconfig.Error)
}

// GetOFPort indicates an expected call of GetOFPort.
func (mr *MockOVSBridgeClientMockRecorder) GetOFPort(ifName, waitUntilValid any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOVSDatapathType mocks base method.
func (m *MockOVSBridgeClient) GetOVSDatapathType() ovsconfig.OVSDatapathType {
	_ = "STUB: not implemented"
	return *new(ovsconfig.OVSDatapathType)
}

// GetOVSDatapathType indicates an expected call of GetOVSDatapathType.
func (mr *MockOVSBridgeClientMockRecorder) GetOVSDatapathType() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOVSOtherConfig mocks base method.
func (m *MockOVSBridgeClient) GetOVSOtherConfig() (map[string]string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetOVSOtherConfig indicates an expected call of GetOVSOtherConfig.
func (mr *MockOVSBridgeClientMockRecorder) GetOVSOtherConfig() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOVSVersion mocks base method.
func (m *MockOVSBridgeClient) GetOVSVersion() (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// GetOVSVersion indicates an expected call of GetOVSVersion.
func (mr *MockOVSBridgeClientMockRecorder) GetOVSVersion() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPortData mocks base method.
func (m *MockOVSBridgeClient) GetPortData(portUUID, ifName string) (*ovsconfig.OVSPortData, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetPortData indicates an expected call of GetPortData.
func (mr *MockOVSBridgeClientMockRecorder) GetPortData(portUUID, ifName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPortExternalIDs mocks base method.
func (m *MockOVSBridgeClient) GetPortExternalIDs(portName string) (map[string]string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetPortExternalIDs indicates an expected call of GetPortExternalIDs.
func (mr *MockOVSBridgeClientMockRecorder) GetPortExternalIDs(portName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPortList mocks base method.
func (m *MockOVSBridgeClient) GetPortList() ([]ovsconfig.OVSPortData, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return nil, *new(ovsconfig.Error)
}

// GetPortList indicates an expected call of GetPortList.
func (mr *MockOVSBridgeClientMockRecorder) GetPortList() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsHardwareOffloadEnabled mocks base method.
func (m *MockOVSBridgeClient) IsHardwareOffloadEnabled() bool {
	_ = "STUB: not implemented"
	return false
}

// IsHardwareOffloadEnabled indicates an expected call of IsHardwareOffloadEnabled.
func (mr *MockOVSBridgeClientMockRecorder) IsHardwareOffloadEnabled() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDatapathID mocks base method.
func (m *MockOVSBridgeClient) SetDatapathID(datapathID string) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetDatapathID indicates an expected call of SetDatapathID.
func (mr *MockOVSBridgeClientMockRecorder) SetDatapathID(datapathID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetExternalIDs mocks base method.
func (m *MockOVSBridgeClient) SetExternalIDs(externalIDs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetExternalIDs indicates an expected call of SetExternalIDs.
func (mr *MockOVSBridgeClientMockRecorder) SetExternalIDs(externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetInterfaceMAC mocks base method.
func (m *MockOVSBridgeClient) SetInterfaceMAC(name string, mac net.HardwareAddr) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetInterfaceMAC indicates an expected call of SetInterfaceMAC.
func (mr *MockOVSBridgeClientMockRecorder) SetInterfaceMAC(name, mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetInterfaceMTU mocks base method.
func (m *MockOVSBridgeClient) SetInterfaceMTU(name string, MTU int) error {
	_ = "STUB: not implemented"
	return nil
}

// SetInterfaceMTU indicates an expected call of SetInterfaceMTU.
func (mr *MockOVSBridgeClientMockRecorder) SetInterfaceMTU(name, MTU any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetInterfaceOptions mocks base method.
func (m *MockOVSBridgeClient) SetInterfaceOptions(name string, options map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetInterfaceOptions indicates an expected call of SetInterfaceOptions.
func (mr *MockOVSBridgeClientMockRecorder) SetInterfaceOptions(name, options any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetInterfaceType mocks base method.
func (m *MockOVSBridgeClient) SetInterfaceType(name, ifType string) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetInterfaceType indicates an expected call of SetInterfaceType.
func (mr *MockOVSBridgeClientMockRecorder) SetInterfaceType(name, ifType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetPortExternalIDs mocks base method.
func (m *MockOVSBridgeClient) SetPortExternalIDs(portName string, externalIDs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// SetPortExternalIDs indicates an expected call of SetPortExternalIDs.
func (mr *MockOVSBridgeClientMockRecorder) SetPortExternalIDs(portName, externalIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateOVSOtherConfig mocks base method.
func (m *MockOVSBridgeClient) UpdateOVSOtherConfig(configs map[string]any) ovsconfig.Error {
	_ = "STUB: not implemented"
	return *new(ovsconfig.Error)
}

// UpdateOVSOtherConfig indicates an expected call of UpdateOVSOtherConfig.
func (mr *MockOVSBridgeClientMockRecorder) UpdateOVSOtherConfig(configs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForDatapathID mocks base method.
func (m *MockOVSBridgeClient) WaitForDatapathID(timeout time.Duration) (string, ovsconfig.Error) {
	_ = "STUB: not implemented"
	return "", *new(ovsconfig.Error)
}

// WaitForDatapathID indicates an expected call of WaitForDatapathID.
func (mr *MockOVSBridgeClientMockRecorder) WaitForDatapathID(timeout any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
