// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/flowaggregator/collector (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/flowaggregator/collector/testing/mock_collector.go -package testing antrea.io/antrea/v2/pkg/flowaggregator/collector Interface
//

// Package testing is a generated GoMock package.
package testing

import (
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// GetNumConnsToCollector mocks base method.
	return nil
}

func (m *MockInterface) GetNumConnsToCollector() int64 { _ = "STUB: not implemented"; return 0 }

// GetNumConnsToCollector indicates an expected call of GetNumConnsToCollector.
func (mr *MockInterfaceMockRecorder) GetNumConnsToCollector() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumRecordsReceived mocks base method.
func (m *MockInterface) GetNumRecordsReceived() int64 { _ = "STUB: not implemented"; return 0 }

// GetNumRecordsReceived indicates an expected call of GetNumRecordsReceived.
func (mr *MockInterfaceMockRecorder) GetNumRecordsReceived() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockInterface) Run(stopCh <-chan struct{}) { _ = "STUB: not implemented"; return }

// Run indicates an expected call of Run.
func (mr *MockInterfaceMockRecorder) Run(stopCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
