// Copyright 2019 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package providers

import (
	"github.com/kevinburke/ssh_config"
	"golang.org/x/crypto/ssh"
)

func vagrantPath() (string, error) {
	_ = "STUB: not implemented"
	// TODO: find a better way to get this path?
	return "", nil
}

func importConfig() (*ssh_config.Config, error) { _ = "STUB: not implemented"; return nil, nil }

func convertConfig(inConfig *ssh_config.Config, name string) (string, *ssh.ClientConfig, error) {
	_ = "STUB: not implemented"
	return "", nil, nil
}

// Read the private key identified by identityFile.

// Create the Signer for this private key.

// #nosec G106: we are using ssh.InsecureIgnoreHostKey, but this is test code

func GetSSHConfig(name string) (string, *ssh.ClientConfig, error) {
	_ = "STUB: not implemented"
	// We convert the Vagrant ssh config file (generated by "vagrant ssh-config"), which is an
	// OpenSSH config file, to an instance of ssh.ClientConfig.
	return "", nil, nil
}

type VagrantProvider struct{}

func (provider *VagrantProvider) RunCommandOnNode(nodeName string, cmd string) (
	code int, stdout string, stderr string, err error,
) {
	_ = "STUB: not implemented"
	return 0, "", "", nil
}

func (provider *VagrantProvider) RunCommandOnNodeExt(nodeName, cmd string, envs map[string]string, stdin string, sudo bool) (
	code int, stdout, stderr string, err error) {
	_ = "STUB: not implemented"
	return 0, "", "", nil
}

func (provider *VagrantProvider) GetKubeconfigPath() (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// NewVagrantProvider returns an implementation of ProviderInterface which is suitable for a
// Kubernetes test cluster created with the provided Vagrantfile.
// configPath is unused for the vagrant provider
func NewVagrantProvider(configPath string) (ProviderInterface, error) {
	_ = "STUB: not implemented"
	return *new(ProviderInterface), nil
}
