// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/antrea/v2/multicluster/apis/multicluster/v1alpha1"
	multiclusterv1alpha1 "antrea.io/antrea/v2/multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterInfoImports implements ClusterInfoImportInterface
type fakeClusterInfoImports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterInfoImport, *v1alpha1.ClusterInfoImportList]
	Fake *FakeMulticlusterV1alpha1
}

func newFakeClusterInfoImports(fake *FakeMulticlusterV1alpha1, namespace string) multiclusterv1alpha1.ClusterInfoImportInterface {
	_ = "STUB: not implemented"
	return *new(multiclusterv1alpha1.ClusterInfoImportInterface)
}
