// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/querier (interfaces: AgentQuerier)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/querier/testing/mock_querier.go -package testing antrea.io/antrea/v2/pkg/agent/querier AgentQuerier
//

// Package testing is a generated GoMock package.
package testing

import (
	config "antrea.io/antrea/v2/pkg/agent/config"
	interfacestore "antrea.io/antrea/v2/pkg/agent/interfacestore"
	memberlist "antrea.io/antrea/v2/pkg/agent/memberlist"
	openflow "antrea.io/antrea/v2/pkg/agent/openflow"
	proxy "antrea.io/antrea/v2/pkg/agent/proxy"
	v1beta1 "antrea.io/antrea/v2/pkg/apis/crd/v1beta1"
	ovsctl "antrea.io/antrea/v2/pkg/ovs/ovsctl"
	querier "antrea.io/antrea/v2/pkg/querier"
	gomock "go.uber.org/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
	v1 "k8s.io/client-go/listers/core/v1"
)

// MockAgentQuerier is a mock of AgentQuerier interface.
type MockAgentQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockAgentQuerierMockRecorder
	isgomock struct{}
}

// MockAgentQuerierMockRecorder is the mock recorder for MockAgentQuerier.
type MockAgentQuerierMockRecorder struct {
	mock *MockAgentQuerier
}

// NewMockAgentQuerier creates a new mock instance.
func NewMockAgentQuerier(ctrl *gomock.Controller) *MockAgentQuerier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentQuerier) EXPECT() *MockAgentQuerierMockRecorder {
	_ = "STUB: not implemented"

	// GetAgentInfo mocks base method.
	return nil
}

func (m *MockAgentQuerier) GetAgentInfo(agentInfo *v1beta1.AntreaAgentInfo, partial bool) {
	_ = "STUB: not implemented"
	return
}

// GetAgentInfo indicates an expected call of GetAgentInfo.
func (mr *MockAgentQuerierMockRecorder) GetAgentInfo(agentInfo, partial any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBGPPolicyInfoQuerier mocks base method.
func (m *MockAgentQuerier) GetBGPPolicyInfoQuerier() querier.AgentBGPPolicyInfoQuerier {
	_ = "STUB: not implemented"
	return *new(querier.AgentBGPPolicyInfoQuerier)
}

// GetBGPPolicyInfoQuerier indicates an expected call of GetBGPPolicyInfoQuerier.
func (mr *MockAgentQuerierMockRecorder) GetBGPPolicyInfoQuerier() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceStore mocks base method.
func (m *MockAgentQuerier) GetInterfaceStore() interfacestore.InterfaceStore {
	_ = "STUB: not implemented"
	return *new(interfacestore.InterfaceStore)
}

// GetInterfaceStore indicates an expected call of GetInterfaceStore.
func (mr *MockAgentQuerierMockRecorder) GetInterfaceStore() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetK8sClient mocks base method.
func (m *MockAgentQuerier) GetK8sClient() kubernetes.Interface {
	_ = "STUB: not implemented"
	return *new(kubernetes.Interface)
}

// GetK8sClient indicates an expected call of GetK8sClient.
func (mr *MockAgentQuerierMockRecorder) GetK8sClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMemberlistCluster mocks base method.
func (m *MockAgentQuerier) GetMemberlistCluster() memberlist.Interface {
	_ = "STUB: not implemented"
	return *new(memberlist.Interface)
}

// GetMemberlistCluster indicates an expected call of GetMemberlistCluster.
func (mr *MockAgentQuerierMockRecorder) GetMemberlistCluster() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNetworkConfig mocks base method.
func (m *MockAgentQuerier) GetNetworkConfig() *config.NetworkConfig {
	_ = "STUB: not implemented"
	return nil
}

// GetNetworkConfig indicates an expected call of GetNetworkConfig.
func (mr *MockAgentQuerierMockRecorder) GetNetworkConfig() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNetworkPolicyInfoQuerier mocks base method.
func (m *MockAgentQuerier) GetNetworkPolicyInfoQuerier() querier.AgentNetworkPolicyInfoQuerier {
	_ = "STUB: not implemented"
	return *new(querier.AgentNetworkPolicyInfoQuerier)
}

// GetNetworkPolicyInfoQuerier indicates an expected call of GetNetworkPolicyInfoQuerier.
func (mr *MockAgentQuerierMockRecorder) GetNetworkPolicyInfoQuerier() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeConfig mocks base method.
func (m *MockAgentQuerier) GetNodeConfig() *config.NodeConfig {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeConfig indicates an expected call of GetNodeConfig.
func (mr *MockAgentQuerierMockRecorder) GetNodeConfig() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeLister mocks base method.
func (m *MockAgentQuerier) GetNodeLister() v1.NodeLister {
	_ = "STUB: not implemented"
	return *new(v1.NodeLister)
}

// GetNodeLister indicates an expected call of GetNodeLister.
func (mr *MockAgentQuerierMockRecorder) GetNodeLister() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOVSCtlClient mocks base method.
func (m *MockAgentQuerier) GetOVSCtlClient() ovsctl.OVSCtlClient {
	_ = "STUB: not implemented"
	return *new(ovsctl.OVSCtlClient)
}

// GetOVSCtlClient indicates an expected call of GetOVSCtlClient.
func (mr *MockAgentQuerierMockRecorder) GetOVSCtlClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOpenflowClient mocks base method.
func (m *MockAgentQuerier) GetOpenflowClient() openflow.Client {
	_ = "STUB: not implemented"
	return *new(openflow.Client)
}

// GetOpenflowClient indicates an expected call of GetOpenflowClient.
func (mr *MockAgentQuerierMockRecorder) GetOpenflowClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetProxier mocks base method.
func (m *MockAgentQuerier) GetProxier() proxy.ProxyQuerier {
	_ = "STUB: not implemented"
	return *new(proxy.ProxyQuerier)
}

// GetProxier indicates an expected call of GetProxier.
func (mr *MockAgentQuerierMockRecorder) GetProxier() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
