// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "antrea.io/antrea/v2/pkg/client/clientset/versioned"
	controlplanev1beta2 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/controlplane/v1beta2"
	crdv1alpha1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/crd/v1alpha1"
	crdv1alpha2 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/crd/v1alpha2"
	crdv1beta1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/crd/v1beta1"
	statsv1alpha1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/stats/v1alpha1"
	systemv1beta1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/system/v1beta1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any field management, validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	_ = "STUB: not implemented"
	return nil
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	_ = "STUB: not implemented"

	// IsWatchListSemanticsUnSupported informs the reflector that this client
	// doesn't support WatchList semantics.
	//
	// This is a synthetic method whose sole purpose is to satisfy the optional
	// interface check performed by the reflector.
	// Returning true signals that WatchList can NOT be used.
	// No additional logic is implemented here.
	return *new(testing.ObjectTracker)
}

func (c *Clientset) IsWatchListSemanticsUnSupported() bool { _ = "STUB: not implemented"; return false }

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// ControlplaneV1beta2 retrieves the ControlplaneV1beta2Client
func (c *Clientset) ControlplaneV1beta2() controlplanev1beta2.ControlplaneV1beta2Interface {
	_ = "STUB: not implemented"
	return *new(controlplanev1beta2.ControlplaneV1beta2Interface)
}

// CrdV1alpha1 retrieves the CrdV1alpha1Client
func (c *Clientset) CrdV1alpha1() crdv1alpha1.CrdV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(crdv1alpha1.CrdV1alpha1Interface)
}

// CrdV1alpha2 retrieves the CrdV1alpha2Client
func (c *Clientset) CrdV1alpha2() crdv1alpha2.CrdV1alpha2Interface {
	_ = "STUB: not implemented"
	return *new(crdv1alpha2.CrdV1alpha2Interface)
}

// CrdV1beta1 retrieves the CrdV1beta1Client
func (c *Clientset) CrdV1beta1() crdv1beta1.CrdV1beta1Interface {
	_ = "STUB: not implemented"
	return *new(crdv1beta1.CrdV1beta1Interface)
}

// StatsV1alpha1 retrieves the StatsV1alpha1Client
func (c *Clientset) StatsV1alpha1() statsv1alpha1.StatsV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(statsv1alpha1.StatsV1alpha1Interface)
}

// SystemV1beta1 retrieves the SystemV1beta1Client
func (c *Clientset) SystemV1beta1() systemv1beta1.SystemV1beta1Interface {
	_ = "STUB: not implemented"
	return *new(systemv1beta1.SystemV1beta1Interface)
}
