// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/interfacestore (interfaces: InterfaceStore)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/interfacestore/testing/mock_interfacestore.go -package testing antrea.io/antrea/v2/pkg/agent/interfacestore InterfaceStore
//

// Package testing is a generated GoMock package.
package testing

import (
	interfacestore "antrea.io/antrea/v2/pkg/agent/interfacestore"
	gomock "go.uber.org/mock/gomock"
)

// MockInterfaceStore is a mock of InterfaceStore interface.
type MockInterfaceStore struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceStoreMockRecorder
	isgomock struct{}
}

// MockInterfaceStoreMockRecorder is the mock recorder for MockInterfaceStore.
type MockInterfaceStoreMockRecorder struct {
	mock *MockInterfaceStore
}

// NewMockInterfaceStore creates a new mock instance.
func NewMockInterfaceStore(ctrl *gomock.Controller) *MockInterfaceStore {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceStore) EXPECT() *MockInterfaceStoreMockRecorder {
	_ = "STUB: not implemented"

	// AddInterface mocks base method.
	return nil
}

func (m *MockInterfaceStore) AddInterface(interfaceConfig *interfacestore.InterfaceConfig) {
	_ = "STUB: not implemented"
	return
}

// AddInterface indicates an expected call of AddInterface.
func (mr *MockInterfaceStoreMockRecorder) AddInterface(interfaceConfig any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteInterface mocks base method.
func (m *MockInterfaceStore) DeleteInterface(interfaceConfig *interfacestore.InterfaceConfig) {
	_ = "STUB: not implemented"
	return
}

// DeleteInterface indicates an expected call of DeleteInterface.
func (mr *MockInterfaceStoreMockRecorder) DeleteInterface(interfaceConfig any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerInterface mocks base method.
func (m *MockInterfaceStore) GetContainerInterface(containerID string) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetContainerInterface indicates an expected call of GetContainerInterface.
func (mr *MockInterfaceStoreMockRecorder) GetContainerInterface(containerID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerInterfaceNum mocks base method.
func (m *MockInterfaceStore) GetContainerInterfaceNum() int { _ = "STUB: not implemented"; return 0 }

// GetContainerInterfaceNum indicates an expected call of GetContainerInterfaceNum.
func (mr *MockInterfaceStoreMockRecorder) GetContainerInterfaceNum() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerInterfacesByPod mocks base method.
func (m *MockInterfaceStore) GetContainerInterfacesByPod(podName, podNamespace string) []*interfacestore.InterfaceConfig {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerInterfacesByPod indicates an expected call of GetContainerInterfacesByPod.
func (mr *MockInterfaceStoreMockRecorder) GetContainerInterfacesByPod(podName, podNamespace any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterface mocks base method.
func (m *MockInterfaceStore) GetInterface(interfaceKey string) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetInterface indicates an expected call of GetInterface.
func (mr *MockInterfaceStoreMockRecorder) GetInterface(interfaceKey any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceByIP mocks base method.
func (m *MockInterfaceStore) GetInterfaceByIP(interfaceIP string) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetInterfaceByIP indicates an expected call of GetInterfaceByIP.
func (mr *MockInterfaceStoreMockRecorder) GetInterfaceByIP(interfaceIP any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceByName mocks base method.
func (m *MockInterfaceStore) GetInterfaceByName(interfaceName string) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetInterfaceByName indicates an expected call of GetInterfaceByName.
func (mr *MockInterfaceStoreMockRecorder) GetInterfaceByName(interfaceName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceByOFPort mocks base method.
func (m *MockInterfaceStore) GetInterfaceByOFPort(ofPort uint32) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetInterfaceByOFPort indicates an expected call of GetInterfaceByOFPort.
func (mr *MockInterfaceStoreMockRecorder) GetInterfaceByOFPort(ofPort any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceKeysByType mocks base method.
func (m *MockInterfaceStore) GetInterfaceKeysByType(interfaceType interfacestore.InterfaceType) []string {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceKeysByType indicates an expected call of GetInterfaceKeysByType.
func (mr *MockInterfaceStoreMockRecorder) GetInterfaceKeysByType(interfaceType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfacesByEntity mocks base method.
func (m *MockInterfaceStore) GetInterfacesByEntity(name, namespace string) []*interfacestore.InterfaceConfig {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfacesByEntity indicates an expected call of GetInterfacesByEntity.
func (mr *MockInterfaceStoreMockRecorder) GetInterfacesByEntity(name, namespace any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfacesByType mocks base method.
func (m *MockInterfaceStore) GetInterfacesByType(interfaceType interfacestore.InterfaceType) []*interfacestore.InterfaceConfig {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfacesByType indicates an expected call of GetInterfacesByType.
func (mr *MockInterfaceStoreMockRecorder) GetInterfacesByType(interfaceType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeTunnelInterface mocks base method.
func (m *MockInterfaceStore) GetNodeTunnelInterface(nodeName string) (*interfacestore.InterfaceConfig, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// GetNodeTunnelInterface indicates an expected call of GetNodeTunnelInterface.
func (mr *MockInterfaceStoreMockRecorder) GetNodeTunnelInterface(nodeName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *MockInterfaceStore) Initialize(interfaces []*interfacestore.InterfaceConfig) {
	_ = "STUB: not implemented"
	return
}

// Initialize indicates an expected call of Initialize.
func (mr *MockInterfaceStoreMockRecorder) Initialize(interfaces any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Len mocks base method.
func (m *MockInterfaceStore) Len() int { _ = "STUB: not implemented"; return 0 }

// Len indicates an expected call of Len.
func (mr *MockInterfaceStoreMockRecorder) Len() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ListInterfaces mocks base method.
func (m *MockInterfaceStore) ListInterfaces() []*interfacestore.InterfaceConfig {
	_ = "STUB: not implemented"
	return nil
}

// ListInterfaces indicates an expected call of ListInterfaces.
func (mr *MockInterfaceStoreMockRecorder) ListInterfaces() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateInterface mocks base method.
func (m *MockInterfaceStore) UpdateInterface(interfaceConfig *interfacestore.InterfaceConfig) {
	_ = "STUB: not implemented"
	return
}

// UpdateInterface indicates an expected call of UpdateInterface.
func (mr *MockInterfaceStoreMockRecorder) UpdateInterface(interfaceConfig any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
