// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/multicast (interfaces: RouteInterface)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/multicast/testing/mock_multicast.go -package testing antrea.io/antrea/v2/pkg/agent/multicast RouteInterface
//

// Package testing is a generated GoMock package.
package testing

import (
	net "net"

	gomock "go.uber.org/mock/gomock"
)

// MockRouteInterface is a mock of RouteInterface interface.
type MockRouteInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRouteInterfaceMockRecorder
	isgomock struct{}
}

// MockRouteInterfaceMockRecorder is the mock recorder for MockRouteInterface.
type MockRouteInterfaceMockRecorder struct {
	mock *MockRouteInterface
}

// NewMockRouteInterface creates a new mock instance.
func NewMockRouteInterface(ctrl *gomock.Controller) *MockRouteInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteInterface) EXPECT() *MockRouteInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// AddMrouteEntry mocks base method.
	return nil
}

func (m *MockRouteInterface) AddMrouteEntry(src, group net.IP, iif uint16, oifs []uint16) error {
	_ = "STUB: not implemented"
	return nil
}

// AddMrouteEntry indicates an expected call of AddMrouteEntry.
func (mr *MockRouteInterfaceMockRecorder) AddMrouteEntry(src, group, iif, oifs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AllocateVIFs mocks base method.
func (m *MockRouteInterface) AllocateVIFs(interfaceNames []string, startVIF uint16) ([]uint16, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AllocateVIFs indicates an expected call of AllocateVIFs.
func (mr *MockRouteInterfaceMockRecorder) AllocateVIFs(interfaceNames, startVIF any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DelMrouteEntry mocks base method.
func (m *MockRouteInterface) DelMrouteEntry(src, group net.IP, iif uint16) error {
	_ = "STUB: not implemented"
	return nil
}

// DelMrouteEntry indicates an expected call of DelMrouteEntry.
func (mr *MockRouteInterfaceMockRecorder) DelMrouteEntry(src, group, iif any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FlushMRoute mocks base method.
func (m *MockRouteInterface) FlushMRoute() { _ = "STUB: not implemented"; return }

// FlushMRoute indicates an expected call of FlushMRoute.
func (mr *MockRouteInterfaceMockRecorder) FlushMRoute() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFD mocks base method.
func (m *MockRouteInterface) GetFD() int { _ = "STUB: not implemented"; return 0 }

// GetFD indicates an expected call of GetFD.
func (mr *MockRouteInterfaceMockRecorder) GetFD() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMroutePacketCount mocks base method.
func (m *MockRouteInterface) GetMroutePacketCount(src, group net.IP) (uint32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetMroutePacketCount indicates an expected call of GetMroutePacketCount.
func (mr *MockRouteInterfaceMockRecorder) GetMroutePacketCount(src, group any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MulticastInterfaceJoinMgroup mocks base method.
func (m *MockRouteInterface) MulticastInterfaceJoinMgroup(mgroup, ifaceIP net.IP, ifaceName string) error {
	_ = "STUB: not implemented"
	return nil
}

// MulticastInterfaceJoinMgroup indicates an expected call of MulticastInterfaceJoinMgroup.
func (mr *MockRouteInterfaceMockRecorder) MulticastInterfaceJoinMgroup(mgroup, ifaceIP, ifaceName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MulticastInterfaceLeaveMgroup mocks base method.
func (m *MockRouteInterface) MulticastInterfaceLeaveMgroup(mgroup, ifaceIP net.IP, ifaceName string) error {
	_ = "STUB: not implemented"
	return nil
}

// MulticastInterfaceLeaveMgroup indicates an expected call of MulticastInterfaceLeaveMgroup.
func (mr *MockRouteInterfaceMockRecorder) MulticastInterfaceLeaveMgroup(mgroup, ifaceIP, ifaceName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
