// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/ipassigner (interfaces: IPAssigner)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/ipassigner/testing/mock_ipassigner.go -package testing antrea.io/antrea/v2/pkg/agent/ipassigner IPAssigner
//

// Package testing is a generated GoMock package.
package testing

import (
	v1beta1 "antrea.io/antrea/v2/pkg/apis/crd/v1beta1"
	gomock "go.uber.org/mock/gomock"
)

// MockIPAssigner is a mock of IPAssigner interface.
type MockIPAssigner struct {
	ctrl     *gomock.Controller
	recorder *MockIPAssignerMockRecorder
	isgomock struct{}
}

// MockIPAssignerMockRecorder is the mock recorder for MockIPAssigner.
type MockIPAssignerMockRecorder struct {
	mock *MockIPAssigner
}

// NewMockIPAssigner creates a new mock instance.
func NewMockIPAssigner(ctrl *gomock.Controller) *MockIPAssigner {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPAssigner) EXPECT() *MockIPAssignerMockRecorder {
	_ = "STUB: not implemented"

	// AssignIP mocks base method.
	return nil
}

func (m *MockIPAssigner) AssignIP(ip string, subnetInfo *v1beta1.SubnetInfo, forceAdvertise bool) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// AssignIP indicates an expected call of AssignIP.
func (mr *MockIPAssignerMockRecorder) AssignIP(ip, subnetInfo, forceAdvertise any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AssignedIPs mocks base method.
func (m *MockIPAssigner) AssignedIPs() map[string]*v1beta1.SubnetInfo {
	_ = "STUB: not implemented"
	return nil
}

// AssignedIPs indicates an expected call of AssignedIPs.
func (mr *MockIPAssignerMockRecorder) AssignedIPs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInterfaceID mocks base method.
func (m *MockIPAssigner) GetInterfaceID(subnetInfo *v1beta1.SubnetInfo) (int, bool) {
	_ = "STUB: not implemented"
	return 0, false
}

// GetInterfaceID indicates an expected call of GetInterfaceID.
func (mr *MockIPAssignerMockRecorder) GetInterfaceID(subnetInfo any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InitIPs mocks base method.
func (m *MockIPAssigner) InitIPs(arg0 map[string]*v1beta1.SubnetInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// InitIPs indicates an expected call of InitIPs.
func (mr *MockIPAssignerMockRecorder) InitIPs(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockIPAssigner) Run(arg0 <-chan struct{}) { _ = "STUB: not implemented"; return }

// Run indicates an expected call of Run.
func (mr *MockIPAssignerMockRecorder) Run(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnassignIP mocks base method.
func (m *MockIPAssigner) UnassignIP(ip string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// UnassignIP indicates an expected call of UnassignIP.
func (mr *MockIPAssignerMockRecorder) UnassignIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
