// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/antrea/v2/pkg/apis/stats/v1alpha1"
	statsv1alpha1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/stats/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAntreaClusterNetworkPolicyStats implements AntreaClusterNetworkPolicyStatsInterface
type fakeAntreaClusterNetworkPolicyStats struct {
	*gentype.FakeClientWithList[*v1alpha1.AntreaClusterNetworkPolicyStats, *v1alpha1.AntreaClusterNetworkPolicyStatsList]
	Fake *FakeStatsV1alpha1
}

func newFakeAntreaClusterNetworkPolicyStats(fake *FakeStatsV1alpha1) statsv1alpha1.AntreaClusterNetworkPolicyStatsInterface {
	_ = "STUB: not implemented"
	return *new(statsv1alpha1.AntreaClusterNetworkPolicyStatsInterface)
}
