// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/util/netlink (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/util/netlink/testing/mock_netlink_linux.go -package testing antrea.io/antrea/v2/pkg/agent/util/netlink Interface
//

// Package testing is a generated GoMock package.
package testing

import (
	net "net"

	netlink "github.com/vishvananda/netlink"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// AddrAdd mocks base method.
	return nil
}

func (m *MockInterface) AddrAdd(link netlink.Link, addr *netlink.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// AddrAdd indicates an expected call of AddrAdd.
func (mr *MockInterfaceMockRecorder) AddrAdd(link, addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddrDel mocks base method.
func (m *MockInterface) AddrDel(link netlink.Link, addr *netlink.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// AddrDel indicates an expected call of AddrDel.
func (mr *MockInterfaceMockRecorder) AddrDel(link, addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddrList mocks base method.
func (m *MockInterface) AddrList(link netlink.Link, family int) ([]netlink.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddrList indicates an expected call of AddrList.
func (mr *MockInterfaceMockRecorder) AddrList(link, family any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddrReplace mocks base method.
func (m *MockInterface) AddrReplace(link netlink.Link, addr *netlink.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// AddrReplace indicates an expected call of AddrReplace.
func (mr *MockInterfaceMockRecorder) AddrReplace(link, addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ConntrackDeleteFilter mocks base method.
func (m *MockInterface) ConntrackDeleteFilter(table netlink.ConntrackTableType, family netlink.InetFamily, filter netlink.CustomConntrackFilter) (uint, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ConntrackDeleteFilter indicates an expected call of ConntrackDeleteFilter.
func (mr *MockInterfaceMockRecorder) ConntrackDeleteFilter(table, family, filter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkAddAltName mocks base method.
func (m *MockInterface) LinkAddAltName(link netlink.Link, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkAddAltName indicates an expected call of LinkAddAltName.
func (mr *MockInterfaceMockRecorder) LinkAddAltName(link, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkByIndex mocks base method.
func (m *MockInterface) LinkByIndex(index int) (netlink.Link, error) {
	_ = "STUB: not implemented"
	return *new(netlink.Link), nil
}

// LinkByIndex indicates an expected call of LinkByIndex.
func (mr *MockInterfaceMockRecorder) LinkByIndex(index any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkByName mocks base method.
func (m *MockInterface) LinkByName(name string) (netlink.Link, error) {
	_ = "STUB: not implemented"
	return *new(netlink.Link), nil
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockInterfaceMockRecorder) LinkByName(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkDelAltName mocks base method.
func (m *MockInterface) LinkDelAltName(link netlink.Link, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkDelAltName indicates an expected call of LinkDelAltName.
func (mr *MockInterfaceMockRecorder) LinkDelAltName(link, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkList mocks base method.
func (m *MockInterface) LinkList() ([]netlink.Link, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LinkList indicates an expected call of LinkList.
func (mr *MockInterfaceMockRecorder) LinkList() *gomock.Call { _ = "STUB: not implemented"; return nil }

// LinkSetAlias mocks base method.
func (m *MockInterface) LinkSetAlias(link netlink.Link, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetAlias indicates an expected call of LinkSetAlias.
func (mr *MockInterfaceMockRecorder) LinkSetAlias(link, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetDown mocks base method.
func (m *MockInterface) LinkSetDown(link netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkSetDown indicates an expected call of LinkSetDown.
func (mr *MockInterfaceMockRecorder) LinkSetDown(link any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetHardwareAddr mocks base method.
func (m *MockInterface) LinkSetHardwareAddr(link netlink.Link, hwaddr net.HardwareAddr) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetHardwareAddr indicates an expected call of LinkSetHardwareAddr.
func (mr *MockInterfaceMockRecorder) LinkSetHardwareAddr(link, hwaddr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetMTU mocks base method.
func (m *MockInterface) LinkSetMTU(link netlink.Link, mtu int) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetMTU indicates an expected call of LinkSetMTU.
func (mr *MockInterfaceMockRecorder) LinkSetMTU(link, mtu any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetName mocks base method.
func (m *MockInterface) LinkSetName(link netlink.Link, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetName indicates an expected call of LinkSetName.
func (mr *MockInterfaceMockRecorder) LinkSetName(link, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetNsFd mocks base method.
func (m *MockInterface) LinkSetNsFd(link netlink.Link, fd int) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetNsFd indicates an expected call of LinkSetNsFd.
func (mr *MockInterfaceMockRecorder) LinkSetNsFd(link, fd any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LinkSetUp mocks base method.
func (m *MockInterface) LinkSetUp(link netlink.Link) error { _ = "STUB: not implemented"; return nil }

// LinkSetUp indicates an expected call of LinkSetUp.
func (mr *MockInterfaceMockRecorder) LinkSetUp(link any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeighDel mocks base method.
func (m *MockInterface) NeighDel(neigh *netlink.Neigh) error { _ = "STUB: not implemented"; return nil }

// NeighDel indicates an expected call of NeighDel.
func (mr *MockInterfaceMockRecorder) NeighDel(neigh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeighList mocks base method.
func (m *MockInterface) NeighList(linkIndex, family int) ([]netlink.Neigh, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NeighList indicates an expected call of NeighList.
func (mr *MockInterfaceMockRecorder) NeighList(linkIndex, family any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeighListExecute mocks base method.
func (m *MockInterface) NeighListExecute(msg netlink.Ndmsg) ([]netlink.Neigh, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NeighListExecute indicates an expected call of NeighListExecute.
func (mr *MockInterfaceMockRecorder) NeighListExecute(msg any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeighSet mocks base method.
func (m *MockInterface) NeighSet(neigh *netlink.Neigh) error { _ = "STUB: not implemented"; return nil }

// NeighSet indicates an expected call of NeighSet.
func (mr *MockInterfaceMockRecorder) NeighSet(neigh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteAdd mocks base method.
func (m *MockInterface) RouteAdd(route *netlink.Route) error { _ = "STUB: not implemented"; return nil }

// RouteAdd indicates an expected call of RouteAdd.
func (mr *MockInterfaceMockRecorder) RouteAdd(route any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteDel mocks base method.
func (m *MockInterface) RouteDel(route *netlink.Route) error { _ = "STUB: not implemented"; return nil }

// RouteDel indicates an expected call of RouteDel.
func (mr *MockInterfaceMockRecorder) RouteDel(route any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteList mocks base method.
func (m *MockInterface) RouteList(link netlink.Link, family int) ([]netlink.Route, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RouteList indicates an expected call of RouteList.
func (mr *MockInterfaceMockRecorder) RouteList(link, family any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteListFiltered mocks base method.
func (m *MockInterface) RouteListFiltered(family int, filter *netlink.Route, filterMask uint64) ([]netlink.Route, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RouteListFiltered indicates an expected call of RouteListFiltered.
func (mr *MockInterfaceMockRecorder) RouteListFiltered(family, filter, filterMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouteReplace mocks base method.
func (m *MockInterface) RouteReplace(route *netlink.Route) error {
	_ = "STUB: not implemented"
	return nil
}

// RouteReplace indicates an expected call of RouteReplace.
func (mr *MockInterfaceMockRecorder) RouteReplace(route any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleAdd mocks base method.
func (m *MockInterface) RuleAdd(rule *netlink.Rule) error { _ = "STUB: not implemented"; return nil }

// RuleAdd indicates an expected call of RuleAdd.
func (mr *MockInterfaceMockRecorder) RuleAdd(rule any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleDel mocks base method.
func (m *MockInterface) RuleDel(rule *netlink.Rule) error { _ = "STUB: not implemented"; return nil }

// RuleDel indicates an expected call of RuleDel.
func (mr *MockInterfaceMockRecorder) RuleDel(rule any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuleList mocks base method.
func (m *MockInterface) RuleList(family int) ([]netlink.Rule, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuleList indicates an expected call of RuleList.
func (mr *MockInterfaceMockRecorder) RuleList(family any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
