// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/ovs/openflow (interfaces: Bridge,Table,Flow,Action,CTAction,FlowBuilder,Group,BucketBuilder,PacketOutBuilder,Meter,MeterBandBuilder)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/ovs/openflow/testing/mock_openflow.go -package testing antrea.io/antrea/v2/pkg/ovs/openflow Bridge,Table,Flow,Action,CTAction,FlowBuilder,Group,BucketBuilder,PacketOutBuilder,Meter,MeterBandBuilder
//

// Package testing is a generated GoMock package.
package testing

import (
	net "net"

	openflow "antrea.io/antrea/v2/pkg/ovs/openflow"
	openflow15 "antrea.io/libOpenflow/openflow15"
	protocol "antrea.io/libOpenflow/protocol"
	util "antrea.io/libOpenflow/util"
	ofctrl "antrea.io/ofnet/ofctrl"
	gomock "go.uber.org/mock/gomock"
)

// MockBridge is a mock of Bridge interface.
type MockBridge struct {
	ctrl     *gomock.Controller
	recorder *MockBridgeMockRecorder
	isgomock struct{}
}

// MockBridgeMockRecorder is the mock recorder for MockBridge.
type MockBridgeMockRecorder struct {
	mock *MockBridge
}

// NewMockBridge creates a new mock instance.
func NewMockBridge(ctrl *gomock.Controller) *MockBridge { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBridge) EXPECT() *MockBridgeMockRecorder {
	_ = "STUB: not implemented"

	// AddFlowsInBundle mocks base method.
	return nil
}

func (m *MockBridge) AddFlowsInBundle(addflows, modFlows, delFlows []*openflow15.FlowMod) error {
	_ = "STUB: not implemented"
	return nil
}

// AddFlowsInBundle indicates an expected call of AddFlowsInBundle.
func (mr *MockBridgeMockRecorder) AddFlowsInBundle(addflows, modFlows, delFlows any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddOFEntriesInBundle mocks base method.
func (m *MockBridge) AddOFEntriesInBundle(addEntries, modEntries, delEntries []openflow.OFEntry) error {
	_ = "STUB: not implemented"
	return nil
}

// AddOFEntriesInBundle indicates an expected call of AddOFEntriesInBundle.
func (mr *MockBridgeMockRecorder) AddOFEntriesInBundle(addEntries, modEntries, delEntries any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BuildPacketOut mocks base method.
func (m *MockBridge) BuildPacketOut() openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// BuildPacketOut indicates an expected call of BuildPacketOut.
func (mr *MockBridgeMockRecorder) BuildPacketOut() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connect mocks base method.
func (m *MockBridge) Connect(maxRetrySec int, connectCh chan struct{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Connect indicates an expected call of Connect.
func (mr *MockBridgeMockRecorder) Connect(maxRetrySec, connectCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFlowsByCookie mocks base method.
func (m *MockBridge) DeleteFlowsByCookie(cookieID, cookieMask uint64) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFlowsByCookie indicates an expected call of DeleteFlowsByCookie.
func (mr *MockBridgeMockRecorder) DeleteFlowsByCookie(cookieID, cookieMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteGroupAll mocks base method.
func (m *MockBridge) DeleteGroupAll() error { _ = "STUB: not implemented"; return nil }

// DeleteGroupAll indicates an expected call of DeleteGroupAll.
func (mr *MockBridgeMockRecorder) DeleteGroupAll() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteMeterAll mocks base method.
func (m *MockBridge) DeleteMeterAll() error { _ = "STUB: not implemented"; return nil }

// DeleteMeterAll indicates an expected call of DeleteMeterAll.
func (mr *MockBridgeMockRecorder) DeleteMeterAll() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Disconnect mocks base method.
func (m *MockBridge) Disconnect() error { _ = "STUB: not implemented"; return nil }

// Disconnect indicates an expected call of Disconnect.
func (mr *MockBridgeMockRecorder) Disconnect() *gomock.Call { _ = "STUB: not implemented"; return nil }

// DumpFlows mocks base method.
func (m *MockBridge) DumpFlows(cookieID, cookieMask uint64) (map[uint64]*openflow.FlowStates, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DumpFlows indicates an expected call of DumpFlows.
func (mr *MockBridgeMockRecorder) DumpFlows(cookieID, cookieMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DumpTableStatus mocks base method.
func (m *MockBridge) DumpTableStatus() []openflow.TableStatus {
	_ = "STUB: not implemented"
	return nil
}

// DumpTableStatus indicates an expected call of DumpTableStatus.
func (mr *MockBridgeMockRecorder) DumpTableStatus() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMeterStats mocks base method.
func (m *MockBridge) GetMeterStats(handleMeterStatsReply func(int, int64)) error {
	_ = "STUB: not implemented"
	return nil
}

// GetMeterStats indicates an expected call of GetMeterStats.
func (mr *MockBridgeMockRecorder) GetMeterStats(handleMeterStatsReply any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTableByID mocks base method.
func (m *MockBridge) GetTableByID(id uint8) (openflow.Table, error) {
	_ = "STUB: not implemented"
	return *new(openflow.Table), nil
}

// GetTableByID indicates an expected call of GetTableByID.
func (mr *MockBridgeMockRecorder) GetTableByID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsConnected mocks base method.
func (m *MockBridge) IsConnected() bool { _ = "STUB: not implemented"; return false }

// IsConnected indicates an expected call of IsConnected.
func (mr *MockBridgeMockRecorder) IsConnected() *gomock.Call { _ = "STUB: not implemented"; return nil }

// NewGroup mocks base method.
func (m *MockBridge) NewGroup(id openflow.GroupIDType) openflow.Group {
	_ = "STUB: not implemented"
	return *new(openflow.Group)
}

// NewGroup indicates an expected call of NewGroup.
func (mr *MockBridgeMockRecorder) NewGroup(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewGroupTypeAll mocks base method.
func (m *MockBridge) NewGroupTypeAll(id openflow.GroupIDType) openflow.Group {
	_ = "STUB: not implemented"
	return *new(openflow.Group)
}

// NewGroupTypeAll indicates an expected call of NewGroupTypeAll.
func (mr *MockBridgeMockRecorder) NewGroupTypeAll(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMeter mocks base method.
func (m *MockBridge) NewMeter(id openflow.MeterIDType, flags ofctrl.MeterFlag) openflow.Meter {
	_ = "STUB: not implemented"
	return *new(openflow.Meter)
}

// NewMeter indicates an expected call of NewMeter.
func (mr *MockBridgeMockRecorder) NewMeter(id, flags any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewTable mocks base method.
func (m *MockBridge) NewTable(table openflow.Table, next uint8, missAction openflow.MissActionType) openflow.Table {
	_ = "STUB: not implemented"
	return *new(openflow.Table)
}

// NewTable indicates an expected call of NewTable.
func (mr *MockBridgeMockRecorder) NewTable(table, next, missAction any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumePacket mocks base method.
func (m *MockBridge) ResumePacket(packetIn *ofctrl.PacketIn) error {
	_ = "STUB: not implemented"
	return nil
}

// ResumePacket indicates an expected call of ResumePacket.
func (mr *MockBridgeMockRecorder) ResumePacket(packetIn any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendPacketOut mocks base method.
func (m *MockBridge) SendPacketOut(packetOut *ofctrl.PacketOut) error {
	_ = "STUB: not implemented"
	return nil
}

// SendPacketOut indicates an expected call of SendPacketOut.
func (mr *MockBridgeMockRecorder) SendPacketOut(packetOut any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribePacketIn mocks base method.
func (m *MockBridge) SubscribePacketIn(category uint8, pktInQueue *openflow.PacketInQueue) error {
	_ = "STUB: not implemented"
	return nil
}

// SubscribePacketIn indicates an expected call of SubscribePacketIn.
func (mr *MockBridgeMockRecorder) SubscribePacketIn(category, pktInQueue any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribePortStatusConsumer mocks base method.
func (m *MockBridge) SubscribePortStatusConsumer(statusCh chan *openflow15.PortStatus) {
	_ = "STUB: not implemented"
	return
}

// SubscribePortStatusConsumer indicates an expected call of SubscribePortStatusConsumer.
func (mr *MockBridgeMockRecorder) SubscribePortStatusConsumer(statusCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTable is a mock of Table interface.
type MockTable struct {
	ctrl     *gomock.Controller
	recorder *MockTableMockRecorder
	isgomock struct{}
}

// MockTableMockRecorder is the mock recorder for MockTable.
type MockTableMockRecorder struct {
	mock *MockTable
}

// NewMockTable creates a new mock instance.
func NewMockTable(ctrl *gomock.Controller) *MockTable { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTable) EXPECT() *MockTableMockRecorder {
	_ = "STUB: not implemented"

	// BuildFlow mocks base method.
	return nil
}

func (m *MockTable) BuildFlow(priority uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// BuildFlow indicates an expected call of BuildFlow.
func (mr *MockTableMockRecorder) BuildFlow(priority any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetID mocks base method.
func (m *MockTable) GetID() uint8 { _ = "STUB: not implemented"; return 0 }

// GetID indicates an expected call of GetID.
func (mr *MockTableMockRecorder) GetID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetMissAction mocks base method.
func (m *MockTable) GetMissAction() openflow.MissActionType {
	_ = "STUB: not implemented"
	return *new(openflow.MissActionType)
}

// GetMissAction indicates an expected call of GetMissAction.
func (mr *MockTableMockRecorder) GetMissAction() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetName mocks base method.
func (m *MockTable) GetName() string { _ = "STUB: not implemented"; return "" }

// GetName indicates an expected call of GetName.
func (mr *MockTableMockRecorder) GetName() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetNext mocks base method.
func (m *MockTable) GetNext() uint8 { _ = "STUB: not implemented"; return 0 }

// GetNext indicates an expected call of GetNext.
func (mr *MockTableMockRecorder) GetNext() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetStageID mocks base method.
func (m *MockTable) GetStageID() openflow.StageID {
	_ = "STUB: not implemented"
	return *new(openflow.StageID)
}

// GetStageID indicates an expected call of GetStageID.
func (mr *MockTableMockRecorder) GetStageID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetMissAction mocks base method.
func (m *MockTable) SetMissAction(action openflow.MissActionType) {
	_ = "STUB: not implemented"
	return
}

// SetMissAction indicates an expected call of SetMissAction.
func (mr *MockTableMockRecorder) SetMissAction(action any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetNext mocks base method.
func (m *MockTable) SetNext(next uint8) { _ = "STUB: not implemented"; return }

// SetNext indicates an expected call of SetNext.
func (mr *MockTableMockRecorder) SetNext(next any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTable mocks base method.
func (m *MockTable) SetTable() { _ = "STUB: not implemented"; return }

// SetTable indicates an expected call of SetTable.
func (mr *MockTableMockRecorder) SetTable() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Status mocks base method.
func (m *MockTable) Status() openflow.TableStatus {
	_ = "STUB: not implemented"
	return *new(openflow.TableStatus)
}

// Status indicates an expected call of Status.
func (mr *MockTableMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockFlow is a mock of Flow interface.
type MockFlow struct {
	ctrl     *gomock.Controller
	recorder *MockFlowMockRecorder
	isgomock struct{}
}

// MockFlowMockRecorder is the mock recorder for MockFlow.
type MockFlowMockRecorder struct {
	mock *MockFlow
}

// NewMockFlow creates a new mock instance.
func NewMockFlow(ctrl *gomock.Controller) *MockFlow { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlow) EXPECT() *MockFlowMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockFlow) Add() error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockFlowMockRecorder) Add() *gomock.Call { _ = "STUB: not implemented"; return nil }

// CopyToBuilder mocks base method.
func (m *MockFlow) CopyToBuilder(priority uint16, copyActions bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// CopyToBuilder indicates an expected call of CopyToBuilder.
func (mr *MockFlowMockRecorder) CopyToBuilder(priority, copyActions any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockFlow) Delete() error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockFlowMockRecorder) Delete() *gomock.Call { _ = "STUB: not implemented"; return nil }

// FlowPriority mocks base method.
func (m *MockFlow) FlowPriority() uint16 { _ = "STUB: not implemented"; return 0 }

// FlowPriority indicates an expected call of FlowPriority.
func (mr *MockFlowMockRecorder) FlowPriority() *gomock.Call { _ = "STUB: not implemented"; return nil }

// FlowProtocol mocks base method.
func (m *MockFlow) FlowProtocol() openflow.Protocol {
	_ = "STUB: not implemented"
	return *new(openflow.Protocol)
}

// FlowProtocol indicates an expected call of FlowProtocol.
func (mr *MockFlowMockRecorder) FlowProtocol() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetBundleMessages mocks base method.
func (m *MockFlow) GetBundleMessages(operation openflow.OFOperation) ([]ofctrl.OpenFlowModMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBundleMessages indicates an expected call of GetBundleMessages.
func (mr *MockFlowMockRecorder) GetBundleMessages(operation any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchString mocks base method.
func (m *MockFlow) MatchString() string { _ = "STUB: not implemented"; return "" }

// MatchString indicates an expected call of MatchString.
func (mr *MockFlowMockRecorder) MatchString() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Modify mocks base method.
func (m *MockFlow) Modify() error { _ = "STUB: not implemented"; return nil }

// Modify indicates an expected call of Modify.
func (mr *MockFlowMockRecorder) Modify() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Reset mocks base method.
func (m *MockFlow) Reset() { _ = "STUB: not implemented"; return }

// Reset indicates an expected call of Reset.
func (mr *MockFlowMockRecorder) Reset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Type mocks base method.
func (m *MockFlow) Type() openflow.EntryType {
	_ = "STUB: not implemented"
	return *new(openflow.EntryType)
}

// Type indicates an expected call of Type.
func (mr *MockFlowMockRecorder) Type() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockAction is a mock of Action interface.
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
	isgomock struct{}
}

// MockActionMockRecorder is the mock recorder for MockAction.
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance.
func NewMockAction(ctrl *gomock.Controller) *MockAction { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	_ = "STUB: not implemented"

	// CT mocks base method.
	return nil
}

func (m *MockAction) CT(commit bool, tableID uint8, zone int, zoneSrcField *openflow.RegField) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// CT indicates an expected call of CT.
func (mr *MockActionMockRecorder) CT(commit, tableID, zone, zoneSrcField any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Conjunction mocks base method.
func (m *MockAction) Conjunction(conjID uint32, clauseID, nClause uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Conjunction indicates an expected call of Conjunction.
func (mr *MockActionMockRecorder) Conjunction(conjID, clauseID, nClause any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DecTTL mocks base method.
func (m *MockAction) DecTTL() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// DecTTL indicates an expected call of DecTTL.
func (mr *MockActionMockRecorder) DecTTL() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Drop mocks base method.
func (m *MockAction) Drop() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Drop indicates an expected call of Drop.
func (mr *MockActionMockRecorder) Drop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GotoStage mocks base method.
func (m *MockAction) GotoStage(stage openflow.StageID) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// GotoStage indicates an expected call of GotoStage.
func (mr *MockActionMockRecorder) GotoStage(stage any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GotoTable mocks base method.
func (m *MockAction) GotoTable(table uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// GotoTable indicates an expected call of GotoTable.
func (mr *MockActionMockRecorder) GotoTable(table any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Group mocks base method.
func (m *MockAction) Group(id openflow.GroupIDType) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Group indicates an expected call of Group.
func (mr *MockActionMockRecorder) Group(id any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Learn mocks base method.
func (m *MockAction) Learn(id uint8, priority, idleTimeout, hardTimeout, finIdleTimeout, finHardTimeout uint16, cookieID uint64) openflow.LearnAction {
	_ = "STUB: not implemented"
	return *new(openflow.LearnAction)
}

// Learn indicates an expected call of Learn.
func (mr *MockActionMockRecorder) Learn(id, priority, idleTimeout, hardTimeout, finIdleTimeout, finHardTimeout, cookieID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadARPOperation mocks base method.
func (m *MockAction) LoadARPOperation(value uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// LoadARPOperation indicates an expected call of LoadARPOperation.
func (mr *MockActionMockRecorder) LoadARPOperation(value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadIPDSCP mocks base method.
func (m *MockAction) LoadIPDSCP(value uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// LoadIPDSCP indicates an expected call of LoadIPDSCP.
func (mr *MockActionMockRecorder) LoadIPDSCP(value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadPktMarkRange mocks base method.
func (m *MockAction) LoadPktMarkRange(value uint32, to *openflow.Range) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// LoadPktMarkRange indicates an expected call of LoadPktMarkRange.
func (mr *MockActionMockRecorder) LoadPktMarkRange(value, to any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadRegMark mocks base method.
func (m *MockAction) LoadRegMark(marks ...*openflow.RegMark) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// LoadRegMark indicates an expected call of LoadRegMark.
func (mr *MockActionMockRecorder) LoadRegMark(marks ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadToRegField mocks base method.
func (m *MockAction) LoadToRegField(field *openflow.RegField, value uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// LoadToRegField indicates an expected call of LoadToRegField.
func (mr *MockActionMockRecorder) LoadToRegField(field, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Meter mocks base method.
func (m *MockAction) Meter(meterID uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Meter indicates an expected call of Meter.
func (mr *MockActionMockRecorder) Meter(meterID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Move mocks base method.
func (m *MockAction) Move(from, to string) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Move indicates an expected call of Move.
func (mr *MockActionMockRecorder) Move(from, to any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MoveRange mocks base method.
func (m *MockAction) MoveRange(fromName, toName string, from, to openflow.Range) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MoveRange indicates an expected call of MoveRange.
func (mr *MockActionMockRecorder) MoveRange(fromName, toName, from, to any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NextTable mocks base method.
func (m *MockAction) NextTable() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// NextTable indicates an expected call of NextTable.
func (mr *MockActionMockRecorder) NextTable() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Normal mocks base method.
func (m *MockAction) Normal() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Normal indicates an expected call of Normal.
func (mr *MockActionMockRecorder) Normal() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Note mocks base method.
func (m *MockAction) Note(notes string) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Note indicates an expected call of Note.
func (mr *MockActionMockRecorder) Note(notes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Output mocks base method.
func (m *MockAction) Output(port uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Output indicates an expected call of Output.
func (mr *MockActionMockRecorder) Output(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OutputFieldRange mocks base method.
func (m *MockAction) OutputFieldRange(from string, rng *openflow.Range) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// OutputFieldRange indicates an expected call of OutputFieldRange.
func (mr *MockActionMockRecorder) OutputFieldRange(from, rng any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OutputInPort mocks base method.
func (m *MockAction) OutputInPort() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// OutputInPort indicates an expected call of OutputInPort.
func (mr *MockActionMockRecorder) OutputInPort() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OutputToRegField mocks base method.
func (m *MockAction) OutputToRegField(field *openflow.RegField) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// OutputToRegField indicates an expected call of OutputToRegField.
func (mr *MockActionMockRecorder) OutputToRegField(field any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PopVLAN mocks base method.
func (m *MockAction) PopVLAN() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// PopVLAN indicates an expected call of PopVLAN.
func (mr *MockActionMockRecorder) PopVLAN() *gomock.Call { _ = "STUB: not implemented"; return nil }

// PushVLAN mocks base method.
func (m *MockAction) PushVLAN(etherType uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// PushVLAN indicates an expected call of PushVLAN.
func (mr *MockActionMockRecorder) PushVLAN(etherType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResubmitToTables mocks base method.
func (m *MockAction) ResubmitToTables(tables ...uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// ResubmitToTables indicates an expected call of ResubmitToTables.
func (mr *MockActionMockRecorder) ResubmitToTables(tables ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendToController mocks base method.
func (m *MockAction) SendToController(userdata []byte, pause bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SendToController indicates an expected call of SendToController.
func (mr *MockActionMockRecorder) SendToController(userdata, pause any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetARPSha mocks base method.
func (m *MockAction) SetARPSha(addr net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetARPSha indicates an expected call of SetARPSha.
func (mr *MockActionMockRecorder) SetARPSha(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetARPSpa mocks base method.
func (m *MockAction) SetARPSpa(addr net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetARPSpa indicates an expected call of SetARPSpa.
func (mr *MockActionMockRecorder) SetARPSpa(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetARPTha mocks base method.
func (m *MockAction) SetARPTha(addr net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetARPTha indicates an expected call of SetARPTha.
func (mr *MockActionMockRecorder) SetARPTha(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetARPTpa mocks base method.
func (m *MockAction) SetARPTpa(addr net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetARPTpa indicates an expected call of SetARPTpa.
func (mr *MockActionMockRecorder) SetARPTpa(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDstIP mocks base method.
func (m *MockAction) SetDstIP(addr net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetDstIP indicates an expected call of SetDstIP.
func (mr *MockActionMockRecorder) SetDstIP(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDstMAC mocks base method.
func (m *MockAction) SetDstMAC(addr net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetDstMAC indicates an expected call of SetDstMAC.
func (mr *MockActionMockRecorder) SetDstMAC(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSrcIP mocks base method.
func (m *MockAction) SetSrcIP(addr net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetSrcIP indicates an expected call of SetSrcIP.
func (mr *MockActionMockRecorder) SetSrcIP(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSrcMAC mocks base method.
func (m *MockAction) SetSrcMAC(addr net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetSrcMAC indicates an expected call of SetSrcMAC.
func (mr *MockActionMockRecorder) SetSrcMAC(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTunnelDst mocks base method.
func (m *MockAction) SetTunnelDst(addr net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetTunnelDst indicates an expected call of SetTunnelDst.
func (mr *MockActionMockRecorder) SetTunnelDst(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTunnelID mocks base method.
func (m *MockAction) SetTunnelID(tunnelID uint64) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetTunnelID indicates an expected call of SetTunnelID.
func (mr *MockActionMockRecorder) SetTunnelID(tunnelID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetVLAN mocks base method.
func (m *MockAction) SetVLAN(vlanID uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetVLAN indicates an expected call of SetVLAN.
func (mr *MockActionMockRecorder) SetVLAN(vlanID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockCTAction is a mock of CTAction interface.
type MockCTAction struct {
	ctrl     *gomock.Controller
	recorder *MockCTActionMockRecorder
	isgomock struct{}
}

// MockCTActionMockRecorder is the mock recorder for MockCTAction.
type MockCTActionMockRecorder struct {
	mock *MockCTAction
}

// NewMockCTAction creates a new mock instance.
func NewMockCTAction(ctrl *gomock.Controller) *MockCTAction { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCTAction) EXPECT() *MockCTActionMockRecorder {
	_ = "STUB: not implemented"

	// CTDone mocks base method.
	return nil
}

func (m *MockCTAction) CTDone() openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// CTDone indicates an expected call of CTDone.
func (mr *MockCTActionMockRecorder) CTDone() *gomock.Call { _ = "STUB: not implemented"; return nil }

// DNAT mocks base method.
func (m *MockCTAction) DNAT(ipRange *openflow.IPRange, portRange *openflow.PortRange) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// DNAT indicates an expected call of DNAT.
func (mr *MockCTActionMockRecorder) DNAT(ipRange, portRange any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadToCtMark mocks base method.
func (m *MockCTAction) LoadToCtMark(marks ...*openflow.CtMark) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// LoadToCtMark indicates an expected call of LoadToCtMark.
func (mr *MockCTActionMockRecorder) LoadToCtMark(marks ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadToLabelField mocks base method.
func (m *MockCTAction) LoadToLabelField(value uint64, labelField *openflow.CtLabel) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// LoadToLabelField indicates an expected call of LoadToLabelField.
func (mr *MockCTActionMockRecorder) LoadToLabelField(value, labelField any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MoveToCtMarkField mocks base method.
func (m *MockCTAction) MoveToCtMarkField(fromRegField *openflow.RegField, ctMark *openflow.CtMarkField) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// MoveToCtMarkField indicates an expected call of MoveToCtMarkField.
func (mr *MockCTActionMockRecorder) MoveToCtMarkField(fromRegField, ctMark any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MoveToLabel mocks base method.
func (m *MockCTAction) MoveToLabel(fromName string, fromRng, labelRng *openflow.Range) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// MoveToLabel indicates an expected call of MoveToLabel.
func (mr *MockCTActionMockRecorder) MoveToLabel(fromName, fromRng, labelRng any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NAT mocks base method.
func (m *MockCTAction) NAT() openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// NAT indicates an expected call of NAT.
func (mr *MockCTActionMockRecorder) NAT() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SNAT mocks base method.
func (m *MockCTAction) SNAT(ipRange *openflow.IPRange, portRange *openflow.PortRange) openflow.CTAction {
	_ = "STUB: not implemented"
	return *new(openflow.CTAction)
}

// SNAT indicates an expected call of SNAT.
func (mr *MockCTActionMockRecorder) SNAT(ipRange, portRange any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockFlowBuilder is a mock of FlowBuilder interface.
type MockFlowBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockFlowBuilderMockRecorder
	isgomock struct{}
}

// MockFlowBuilderMockRecorder is the mock recorder for MockFlowBuilder.
type MockFlowBuilderMockRecorder struct {
	mock *MockFlowBuilder
}

// NewMockFlowBuilder creates a new mock instance.
func NewMockFlowBuilder(ctrl *gomock.Controller) *MockFlowBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowBuilder) EXPECT() *MockFlowBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Action mocks base method.
	return nil
}

func (m *MockFlowBuilder) Action() openflow.Action {
	_ = "STUB: not implemented"
	return *new(openflow.Action)
}

// Action indicates an expected call of Action.
func (mr *MockFlowBuilderMockRecorder) Action() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Cookie mocks base method.
func (m *MockFlowBuilder) Cookie(cookieID uint64) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// Cookie indicates an expected call of Cookie.
func (mr *MockFlowBuilderMockRecorder) Cookie(cookieID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Done mocks base method.
func (m *MockFlowBuilder) Done() openflow.Flow {
	_ = "STUB: not implemented"
	return *new(openflow.Flow)
}

// Done indicates an expected call of Done.
func (mr *MockFlowBuilderMockRecorder) Done() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MatchARPOp mocks base method.
func (m *MockFlowBuilder) MatchARPOp(op uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchARPOp indicates an expected call of MatchARPOp.
func (mr *MockFlowBuilderMockRecorder) MatchARPOp(op any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchARPSha mocks base method.
func (m *MockFlowBuilder) MatchARPSha(mac net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchARPSha indicates an expected call of MatchARPSha.
func (mr *MockFlowBuilderMockRecorder) MatchARPSha(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchARPSpa mocks base method.
func (m *MockFlowBuilder) MatchARPSpa(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchARPSpa indicates an expected call of MatchARPSpa.
func (mr *MockFlowBuilderMockRecorder) MatchARPSpa(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchARPTha mocks base method.
func (m *MockFlowBuilder) MatchARPTha(mac net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchARPTha indicates an expected call of MatchARPTha.
func (mr *MockFlowBuilderMockRecorder) MatchARPTha(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchARPTpa mocks base method.
func (m *MockFlowBuilder) MatchARPTpa(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchARPTpa indicates an expected call of MatchARPTpa.
func (mr *MockFlowBuilderMockRecorder) MatchARPTpa(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTDstIP mocks base method.
func (m *MockFlowBuilder) MatchCTDstIP(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTDstIP indicates an expected call of MatchCTDstIP.
func (mr *MockFlowBuilderMockRecorder) MatchCTDstIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTDstIPNet mocks base method.
func (m *MockFlowBuilder) MatchCTDstIPNet(ipNet net.IPNet) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTDstIPNet indicates an expected call of MatchCTDstIPNet.
func (mr *MockFlowBuilderMockRecorder) MatchCTDstIPNet(ipNet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTDstPort mocks base method.
func (m *MockFlowBuilder) MatchCTDstPort(port uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTDstPort indicates an expected call of MatchCTDstPort.
func (mr *MockFlowBuilderMockRecorder) MatchCTDstPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTLabelField mocks base method.
func (m *MockFlowBuilder) MatchCTLabelField(high, low uint64, field *openflow.CtLabel) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTLabelField indicates an expected call of MatchCTLabelField.
func (mr *MockFlowBuilderMockRecorder) MatchCTLabelField(high, low, field any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTMark mocks base method.
func (m *MockFlowBuilder) MatchCTMark(marks ...*openflow.CtMark) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTMark indicates an expected call of MatchCTMark.
func (mr *MockFlowBuilderMockRecorder) MatchCTMark(marks ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTProtocol mocks base method.
func (m *MockFlowBuilder) MatchCTProtocol(proto openflow.Protocol) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTProtocol indicates an expected call of MatchCTProtocol.
func (mr *MockFlowBuilderMockRecorder) MatchCTProtocol(proto any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTSrcIP mocks base method.
func (m *MockFlowBuilder) MatchCTSrcIP(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTSrcIP indicates an expected call of MatchCTSrcIP.
func (mr *MockFlowBuilderMockRecorder) MatchCTSrcIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTSrcIPNet mocks base method.
func (m *MockFlowBuilder) MatchCTSrcIPNet(ipnet net.IPNet) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTSrcIPNet indicates an expected call of MatchCTSrcIPNet.
func (mr *MockFlowBuilderMockRecorder) MatchCTSrcIPNet(ipnet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTSrcPort mocks base method.
func (m *MockFlowBuilder) MatchCTSrcPort(port uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTSrcPort indicates an expected call of MatchCTSrcPort.
func (mr *MockFlowBuilderMockRecorder) MatchCTSrcPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTState mocks base method.
func (m *MockFlowBuilder) MatchCTState(ctStates *openflow15.CTStates) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTState indicates an expected call of MatchCTState.
func (mr *MockFlowBuilderMockRecorder) MatchCTState(ctStates any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateDNAT mocks base method.
func (m *MockFlowBuilder) MatchCTStateDNAT(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateDNAT indicates an expected call of MatchCTStateDNAT.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateDNAT(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateEst mocks base method.
func (m *MockFlowBuilder) MatchCTStateEst(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateEst indicates an expected call of MatchCTStateEst.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateEst(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateInv mocks base method.
func (m *MockFlowBuilder) MatchCTStateInv(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateInv indicates an expected call of MatchCTStateInv.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateInv(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateNew mocks base method.
func (m *MockFlowBuilder) MatchCTStateNew(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateNew indicates an expected call of MatchCTStateNew.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateNew(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateRel mocks base method.
func (m *MockFlowBuilder) MatchCTStateRel(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateRel indicates an expected call of MatchCTStateRel.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateRel(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateRpl mocks base method.
func (m *MockFlowBuilder) MatchCTStateRpl(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateRpl indicates an expected call of MatchCTStateRpl.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateRpl(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateSNAT mocks base method.
func (m *MockFlowBuilder) MatchCTStateSNAT(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateSNAT indicates an expected call of MatchCTStateSNAT.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateSNAT(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTStateTrk mocks base method.
func (m *MockFlowBuilder) MatchCTStateTrk(isSet bool) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTStateTrk indicates an expected call of MatchCTStateTrk.
func (mr *MockFlowBuilderMockRecorder) MatchCTStateTrk(isSet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchCTZone mocks base method.
func (m *MockFlowBuilder) MatchCTZone(zone int) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchCTZone indicates an expected call of MatchCTZone.
func (mr *MockFlowBuilderMockRecorder) MatchCTZone(zone any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchConjID mocks base method.
func (m *MockFlowBuilder) MatchConjID(value uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchConjID indicates an expected call of MatchConjID.
func (mr *MockFlowBuilderMockRecorder) MatchConjID(value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchDstIP mocks base method.
func (m *MockFlowBuilder) MatchDstIP(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchDstIP indicates an expected call of MatchDstIP.
func (mr *MockFlowBuilderMockRecorder) MatchDstIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchDstIPNet mocks base method.
func (m *MockFlowBuilder) MatchDstIPNet(ipNet net.IPNet) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchDstIPNet indicates an expected call of MatchDstIPNet.
func (mr *MockFlowBuilderMockRecorder) MatchDstIPNet(ipNet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchDstMAC mocks base method.
func (m *MockFlowBuilder) MatchDstMAC(mac net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchDstMAC indicates an expected call of MatchDstMAC.
func (mr *MockFlowBuilderMockRecorder) MatchDstMAC(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchDstPort mocks base method.
func (m *MockFlowBuilder) MatchDstPort(port uint16, portMask *uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchDstPort indicates an expected call of MatchDstPort.
func (mr *MockFlowBuilderMockRecorder) MatchDstPort(port, portMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchICMPCode mocks base method.
func (m *MockFlowBuilder) MatchICMPCode(icmpCode byte) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchICMPCode indicates an expected call of MatchICMPCode.
func (mr *MockFlowBuilderMockRecorder) MatchICMPCode(icmpCode any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchICMPType mocks base method.
func (m *MockFlowBuilder) MatchICMPType(icmpType byte) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchICMPType indicates an expected call of MatchICMPType.
func (mr *MockFlowBuilderMockRecorder) MatchICMPType(icmpType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchICMPv6Code mocks base method.
func (m *MockFlowBuilder) MatchICMPv6Code(icmp6Code byte) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchICMPv6Code indicates an expected call of MatchICMPv6Code.
func (mr *MockFlowBuilderMockRecorder) MatchICMPv6Code(icmp6Code any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchICMPv6Type mocks base method.
func (m *MockFlowBuilder) MatchICMPv6Type(icmp6Type byte) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchICMPv6Type indicates an expected call of MatchICMPv6Type.
func (mr *MockFlowBuilderMockRecorder) MatchICMPv6Type(icmp6Type any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchIPDSCP mocks base method.
func (m *MockFlowBuilder) MatchIPDSCP(dscp uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchIPDSCP indicates an expected call of MatchIPDSCP.
func (mr *MockFlowBuilderMockRecorder) MatchIPDSCP(dscp any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchIPProtocolValue mocks base method.
func (m *MockFlowBuilder) MatchIPProtocolValue(isIPv6 bool, protoValue uint8) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchIPProtocolValue indicates an expected call of MatchIPProtocolValue.
func (mr *MockFlowBuilderMockRecorder) MatchIPProtocolValue(isIPv6, protoValue any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchInPort mocks base method.
func (m *MockFlowBuilder) MatchInPort(inPort uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchInPort indicates an expected call of MatchInPort.
func (mr *MockFlowBuilderMockRecorder) MatchInPort(inPort any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchPktMark mocks base method.
func (m *MockFlowBuilder) MatchPktMark(value uint32, mask *uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchPktMark indicates an expected call of MatchPktMark.
func (mr *MockFlowBuilderMockRecorder) MatchPktMark(value, mask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchPriority mocks base method.
func (m *MockFlowBuilder) MatchPriority(arg0 uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchPriority indicates an expected call of MatchPriority.
func (mr *MockFlowBuilderMockRecorder) MatchPriority(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchProtocol mocks base method.
func (m *MockFlowBuilder) MatchProtocol(name openflow.Protocol) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchProtocol indicates an expected call of MatchProtocol.
func (mr *MockFlowBuilderMockRecorder) MatchProtocol(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchRegFieldWithValue mocks base method.
func (m *MockFlowBuilder) MatchRegFieldWithValue(field *openflow.RegField, data uint32) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchRegFieldWithValue indicates an expected call of MatchRegFieldWithValue.
func (mr *MockFlowBuilderMockRecorder) MatchRegFieldWithValue(field, data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchRegMark mocks base method.
func (m *MockFlowBuilder) MatchRegMark(marks ...*openflow.RegMark) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchRegMark indicates an expected call of MatchRegMark.
func (mr *MockFlowBuilderMockRecorder) MatchRegMark(marks ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchSrcIP mocks base method.
func (m *MockFlowBuilder) MatchSrcIP(ip net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchSrcIP indicates an expected call of MatchSrcIP.
func (mr *MockFlowBuilderMockRecorder) MatchSrcIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchSrcIPNet mocks base method.
func (m *MockFlowBuilder) MatchSrcIPNet(ipNet net.IPNet) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchSrcIPNet indicates an expected call of MatchSrcIPNet.
func (mr *MockFlowBuilderMockRecorder) MatchSrcIPNet(ipNet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchSrcMAC mocks base method.
func (m *MockFlowBuilder) MatchSrcMAC(mac net.HardwareAddr) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchSrcMAC indicates an expected call of MatchSrcMAC.
func (mr *MockFlowBuilderMockRecorder) MatchSrcMAC(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchSrcPort mocks base method.
func (m *MockFlowBuilder) MatchSrcPort(port uint16, portMask *uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchSrcPort indicates an expected call of MatchSrcPort.
func (mr *MockFlowBuilderMockRecorder) MatchSrcPort(port, portMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchTCPFlags mocks base method.
func (m *MockFlowBuilder) MatchTCPFlags(flag, mask uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchTCPFlags indicates an expected call of MatchTCPFlags.
func (mr *MockFlowBuilderMockRecorder) MatchTCPFlags(flag, mask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchTunnelDst mocks base method.
func (m *MockFlowBuilder) MatchTunnelDst(dstIP net.IP) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchTunnelDst indicates an expected call of MatchTunnelDst.
func (mr *MockFlowBuilderMockRecorder) MatchTunnelDst(dstIP any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchTunnelID mocks base method.
func (m *MockFlowBuilder) MatchTunnelID(tunnelID uint64) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchTunnelID indicates an expected call of MatchTunnelID.
func (mr *MockFlowBuilderMockRecorder) MatchTunnelID(tunnelID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchVLAN mocks base method.
func (m *MockFlowBuilder) MatchVLAN(nonVLAN bool, vlanId uint16, vlanMask *uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchVLAN indicates an expected call of MatchVLAN.
func (mr *MockFlowBuilderMockRecorder) MatchVLAN(nonVLAN, vlanId, vlanMask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MatchXXReg mocks base method.
func (m *MockFlowBuilder) MatchXXReg(regID int, data []byte) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// MatchXXReg indicates an expected call of MatchXXReg.
func (mr *MockFlowBuilderMockRecorder) MatchXXReg(regID, data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHardTimeout mocks base method.
func (m *MockFlowBuilder) SetHardTimeout(timout uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetHardTimeout indicates an expected call of SetHardTimeout.
func (mr *MockFlowBuilderMockRecorder) SetHardTimeout(timout any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIdleTimeout mocks base method.
func (m *MockFlowBuilder) SetIdleTimeout(timeout uint16) openflow.FlowBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.FlowBuilder)
}

// SetIdleTimeout indicates an expected call of SetIdleTimeout.
func (mr *MockFlowBuilderMockRecorder) SetIdleTimeout(timeout any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGroup is a mock of Group interface.
type MockGroup struct {
	ctrl     *gomock.Controller
	recorder *MockGroupMockRecorder
	isgomock struct{}
}

// MockGroupMockRecorder is the mock recorder for MockGroup.
type MockGroupMockRecorder struct {
	mock *MockGroup
}

// NewMockGroup creates a new mock instance.
func NewMockGroup(ctrl *gomock.Controller) *MockGroup { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroup) EXPECT() *MockGroupMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockGroup) Add() error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockGroupMockRecorder) Add() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Bucket mocks base method.
func (m *MockGroup) Bucket() openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// Bucket indicates an expected call of Bucket.
func (mr *MockGroupMockRecorder) Bucket() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Delete mocks base method.
func (m *MockGroup) Delete() error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockGroupMockRecorder) Delete() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetBundleMessages mocks base method.
func (m *MockGroup) GetBundleMessages(operation openflow.OFOperation) ([]ofctrl.OpenFlowModMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBundleMessages indicates an expected call of GetBundleMessages.
func (mr *MockGroupMockRecorder) GetBundleMessages(operation any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetID mocks base method.
func (m *MockGroup) GetID() openflow.GroupIDType {
	_ = "STUB: not implemented"
	return *new(openflow.GroupIDType)
}

// GetID indicates an expected call of GetID.
func (mr *MockGroupMockRecorder) GetID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Modify mocks base method.
func (m *MockGroup) Modify() error { _ = "STUB: not implemented"; return nil }

// Modify indicates an expected call of Modify.
func (mr *MockGroupMockRecorder) Modify() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Reset mocks base method.
func (m *MockGroup) Reset() { _ = "STUB: not implemented"; return }

// Reset indicates an expected call of Reset.
func (mr *MockGroupMockRecorder) Reset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ResetBuckets mocks base method.
func (m *MockGroup) ResetBuckets() openflow.Group {
	_ = "STUB: not implemented"
	return *new(openflow.Group)
}

// ResetBuckets indicates an expected call of ResetBuckets.
func (mr *MockGroupMockRecorder) ResetBuckets() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Type mocks base method.
func (m *MockGroup) Type() openflow.EntryType {
	_ = "STUB: not implemented"
	return *new(openflow.EntryType)
}

// Type indicates an expected call of Type.
func (mr *MockGroupMockRecorder) Type() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockBucketBuilder is a mock of BucketBuilder interface.
type MockBucketBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBucketBuilderMockRecorder
	isgomock struct{}
}

// MockBucketBuilderMockRecorder is the mock recorder for MockBucketBuilder.
type MockBucketBuilderMockRecorder struct {
	mock *MockBucketBuilder
}

// NewMockBucketBuilder creates a new mock instance.
func NewMockBucketBuilder(ctrl *gomock.Controller) *MockBucketBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketBuilder) EXPECT() *MockBucketBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Done mocks base method.
	return nil
}

func (m *MockBucketBuilder) Done() openflow.Group {
	_ = "STUB: not implemented"
	return *new(openflow.Group)
}

// Done indicates an expected call of Done.
func (mr *MockBucketBuilderMockRecorder) Done() *gomock.Call { _ = "STUB: not implemented"; return nil }

// LoadRegMark mocks base method.
func (m *MockBucketBuilder) LoadRegMark(mark *openflow.RegMark) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// LoadRegMark indicates an expected call of LoadRegMark.
func (mr *MockBucketBuilderMockRecorder) LoadRegMark(mark any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadToRegField mocks base method.
func (m *MockBucketBuilder) LoadToRegField(field *openflow.RegField, data uint32) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// LoadToRegField indicates an expected call of LoadToRegField.
func (mr *MockBucketBuilderMockRecorder) LoadToRegField(field, data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadXXReg mocks base method.
func (m *MockBucketBuilder) LoadXXReg(regID int, data []byte) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// LoadXXReg indicates an expected call of LoadXXReg.
func (mr *MockBucketBuilderMockRecorder) LoadXXReg(regID, data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResubmitToTable mocks base method.
func (m *MockBucketBuilder) ResubmitToTable(tableID uint8) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// ResubmitToTable indicates an expected call of ResubmitToTable.
func (mr *MockBucketBuilderMockRecorder) ResubmitToTable(tableID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTunnelDst mocks base method.
func (m *MockBucketBuilder) SetTunnelDst(addr net.IP) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// SetTunnelDst indicates an expected call of SetTunnelDst.
func (mr *MockBucketBuilderMockRecorder) SetTunnelDst(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Weight mocks base method.
func (m *MockBucketBuilder) Weight(val uint16) openflow.BucketBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.BucketBuilder)
}

// Weight indicates an expected call of Weight.
func (mr *MockBucketBuilderMockRecorder) Weight(val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPacketOutBuilder is a mock of PacketOutBuilder interface.
type MockPacketOutBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockPacketOutBuilderMockRecorder
	isgomock struct{}
}

// MockPacketOutBuilderMockRecorder is the mock recorder for MockPacketOutBuilder.
type MockPacketOutBuilderMockRecorder struct {
	mock *MockPacketOutBuilder
}

// NewMockPacketOutBuilder creates a new mock instance.
func NewMockPacketOutBuilder(ctrl *gomock.Controller) *MockPacketOutBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketOutBuilder) EXPECT() *MockPacketOutBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddLoadRegMark mocks base method.
	return nil
}

func (m *MockPacketOutBuilder) AddLoadRegMark(mark *openflow.RegMark) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// AddLoadRegMark indicates an expected call of AddLoadRegMark.
func (mr *MockPacketOutBuilderMockRecorder) AddLoadRegMark(mark any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddResubmitAction mocks base method.
func (m *MockPacketOutBuilder) AddResubmitAction(inPort *uint16, table *uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// AddResubmitAction indicates an expected call of AddResubmitAction.
func (mr *MockPacketOutBuilderMockRecorder) AddResubmitAction(inPort, table any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddSetIPTOSAction mocks base method.
func (m *MockPacketOutBuilder) AddSetIPTOSAction(data uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// AddSetIPTOSAction indicates an expected call of AddSetIPTOSAction.
func (mr *MockPacketOutBuilderMockRecorder) AddSetIPTOSAction(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Done mocks base method.
func (m *MockPacketOutBuilder) Done() *ofctrl.PacketOut { _ = "STUB: not implemented"; return nil }

// Done indicates an expected call of Done.
func (mr *MockPacketOutBuilderMockRecorder) Done() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDstIP mocks base method.
func (m *MockPacketOutBuilder) SetDstIP(ip net.IP) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetDstIP indicates an expected call of SetDstIP.
func (mr *MockPacketOutBuilderMockRecorder) SetDstIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDstMAC mocks base method.
func (m *MockPacketOutBuilder) SetDstMAC(mac net.HardwareAddr) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetDstMAC indicates an expected call of SetDstMAC.
func (mr *MockPacketOutBuilderMockRecorder) SetDstMAC(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetEthPacket mocks base method.
func (m *MockPacketOutBuilder) SetEthPacket(packet *protocol.Ethernet) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetEthPacket indicates an expected call of SetEthPacket.
func (mr *MockPacketOutBuilderMockRecorder) SetEthPacket(packet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetICMPCode mocks base method.
func (m *MockPacketOutBuilder) SetICMPCode(icmpCode uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetICMPCode indicates an expected call of SetICMPCode.
func (mr *MockPacketOutBuilderMockRecorder) SetICMPCode(icmpCode any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetICMPData mocks base method.
func (m *MockPacketOutBuilder) SetICMPData(data []byte) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetICMPData indicates an expected call of SetICMPData.
func (mr *MockPacketOutBuilderMockRecorder) SetICMPData(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetICMPID mocks base method.
func (m *MockPacketOutBuilder) SetICMPID(id uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetICMPID indicates an expected call of SetICMPID.
func (mr *MockPacketOutBuilderMockRecorder) SetICMPID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetICMPSequence mocks base method.
func (m *MockPacketOutBuilder) SetICMPSequence(seq uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetICMPSequence indicates an expected call of SetICMPSequence.
func (mr *MockPacketOutBuilderMockRecorder) SetICMPSequence(seq any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetICMPType mocks base method.
func (m *MockPacketOutBuilder) SetICMPType(icmpType uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetICMPType indicates an expected call of SetICMPType.
func (mr *MockPacketOutBuilderMockRecorder) SetICMPType(icmpType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIPFlags mocks base method.
func (m *MockPacketOutBuilder) SetIPFlags(flags uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetIPFlags indicates an expected call of SetIPFlags.
func (mr *MockPacketOutBuilderMockRecorder) SetIPFlags(flags any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIPHeaderID mocks base method.
func (m *MockPacketOutBuilder) SetIPHeaderID(id uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetIPHeaderID indicates an expected call of SetIPHeaderID.
func (mr *MockPacketOutBuilderMockRecorder) SetIPHeaderID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIPProtocol mocks base method.
func (m *MockPacketOutBuilder) SetIPProtocol(arg0 openflow.Protocol) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetIPProtocol indicates an expected call of SetIPProtocol.
func (mr *MockPacketOutBuilderMockRecorder) SetIPProtocol(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIPProtocolValue mocks base method.
func (m *MockPacketOutBuilder) SetIPProtocolValue(isIPv6 bool, protoValue uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetIPProtocolValue indicates an expected call of SetIPProtocolValue.
func (mr *MockPacketOutBuilderMockRecorder) SetIPProtocolValue(isIPv6, protoValue any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetInport mocks base method.
func (m *MockPacketOutBuilder) SetInport(inPort uint32) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetInport indicates an expected call of SetInport.
func (mr *MockPacketOutBuilderMockRecorder) SetInport(inPort any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetL4Packet mocks base method.
func (m *MockPacketOutBuilder) SetL4Packet(packet util.Message) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetL4Packet indicates an expected call of SetL4Packet.
func (mr *MockPacketOutBuilderMockRecorder) SetL4Packet(packet any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetOutport mocks base method.
func (m *MockPacketOutBuilder) SetOutport(outport uint32) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetOutport indicates an expected call of SetOutport.
func (mr *MockPacketOutBuilderMockRecorder) SetOutport(outport any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSrcIP mocks base method.
func (m *MockPacketOutBuilder) SetSrcIP(ip net.IP) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetSrcIP indicates an expected call of SetSrcIP.
func (mr *MockPacketOutBuilderMockRecorder) SetSrcIP(ip any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSrcMAC mocks base method.
func (m *MockPacketOutBuilder) SetSrcMAC(mac net.HardwareAddr) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetSrcMAC indicates an expected call of SetSrcMAC.
func (mr *MockPacketOutBuilderMockRecorder) SetSrcMAC(mac any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPAckNum mocks base method.
func (m *MockPacketOutBuilder) SetTCPAckNum(ackNum uint32) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPAckNum indicates an expected call of SetTCPAckNum.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPAckNum(ackNum any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPData mocks base method.
func (m *MockPacketOutBuilder) SetTCPData(data []byte) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPData indicates an expected call of SetTCPData.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPData(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPDstPort mocks base method.
func (m *MockPacketOutBuilder) SetTCPDstPort(port uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPDstPort indicates an expected call of SetTCPDstPort.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPDstPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPFlags mocks base method.
func (m *MockPacketOutBuilder) SetTCPFlags(flags uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPFlags indicates an expected call of SetTCPFlags.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPFlags(flags any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPHdrLen mocks base method.
func (m *MockPacketOutBuilder) SetTCPHdrLen(hdrLen uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPHdrLen indicates an expected call of SetTCPHdrLen.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPHdrLen(hdrLen any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPSeqNum mocks base method.
func (m *MockPacketOutBuilder) SetTCPSeqNum(seqNum uint32) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPSeqNum indicates an expected call of SetTCPSeqNum.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPSeqNum(seqNum any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPSrcPort mocks base method.
func (m *MockPacketOutBuilder) SetTCPSrcPort(port uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPSrcPort indicates an expected call of SetTCPSrcPort.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPSrcPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTCPWinSize mocks base method.
func (m *MockPacketOutBuilder) SetTCPWinSize(winSize uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTCPWinSize indicates an expected call of SetTCPWinSize.
func (mr *MockPacketOutBuilderMockRecorder) SetTCPWinSize(winSize any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTTL mocks base method.
func (m *MockPacketOutBuilder) SetTTL(ttl uint8) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetTTL indicates an expected call of SetTTL.
func (mr *MockPacketOutBuilderMockRecorder) SetTTL(ttl any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUDPData mocks base method.
func (m *MockPacketOutBuilder) SetUDPData(data []byte) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetUDPData indicates an expected call of SetUDPData.
func (mr *MockPacketOutBuilderMockRecorder) SetUDPData(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUDPDstPort mocks base method.
func (m *MockPacketOutBuilder) SetUDPDstPort(port uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetUDPDstPort indicates an expected call of SetUDPDstPort.
func (mr *MockPacketOutBuilderMockRecorder) SetUDPDstPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUDPSrcPort mocks base method.
func (m *MockPacketOutBuilder) SetUDPSrcPort(port uint16) openflow.PacketOutBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.PacketOutBuilder)
}

// SetUDPSrcPort indicates an expected call of SetUDPSrcPort.
func (mr *MockPacketOutBuilderMockRecorder) SetUDPSrcPort(port any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMeter is a mock of Meter interface.
type MockMeter struct {
	ctrl     *gomock.Controller
	recorder *MockMeterMockRecorder
	isgomock struct{}
}

// MockMeterMockRecorder is the mock recorder for MockMeter.
type MockMeterMockRecorder struct {
	mock *MockMeter
}

// NewMockMeter creates a new mock instance.
func NewMockMeter(ctrl *gomock.Controller) *MockMeter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeter) EXPECT() *MockMeterMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockMeter) Add() error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockMeterMockRecorder) Add() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Delete mocks base method.
func (m *MockMeter) Delete() error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockMeterMockRecorder) Delete() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetBundleMessages mocks base method.
func (m *MockMeter) GetBundleMessages(operation openflow.OFOperation) ([]ofctrl.OpenFlowModMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBundleMessages indicates an expected call of GetBundleMessages.
func (mr *MockMeterMockRecorder) GetBundleMessages(operation any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MeterBand mocks base method.
func (m *MockMeter) MeterBand() openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// MeterBand indicates an expected call of MeterBand.
func (mr *MockMeterMockRecorder) MeterBand() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Modify mocks base method.
func (m *MockMeter) Modify() error { _ = "STUB: not implemented"; return nil }

// Modify indicates an expected call of Modify.
func (mr *MockMeterMockRecorder) Modify() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Reset mocks base method.
func (m *MockMeter) Reset() { _ = "STUB: not implemented"; return }

// Reset indicates an expected call of Reset.
func (mr *MockMeterMockRecorder) Reset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ResetMeterBands mocks base method.
func (m *MockMeter) ResetMeterBands() openflow.Meter {
	_ = "STUB: not implemented"
	return *new(openflow.Meter)
}

// ResetMeterBands indicates an expected call of ResetMeterBands.
func (mr *MockMeterMockRecorder) ResetMeterBands() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Type mocks base method.
func (m *MockMeter) Type() openflow.EntryType {
	_ = "STUB: not implemented"
	return *new(openflow.EntryType)
}

// Type indicates an expected call of Type.
func (mr *MockMeterMockRecorder) Type() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockMeterBandBuilder is a mock of MeterBandBuilder interface.
type MockMeterBandBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockMeterBandBuilderMockRecorder
	isgomock struct{}
}

// MockMeterBandBuilderMockRecorder is the mock recorder for MockMeterBandBuilder.
type MockMeterBandBuilderMockRecorder struct {
	mock *MockMeterBandBuilder
}

// NewMockMeterBandBuilder creates a new mock instance.
func NewMockMeterBandBuilder(ctrl *gomock.Controller) *MockMeterBandBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterBandBuilder) EXPECT() *MockMeterBandBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Burst mocks base method.
	return nil
}

func (m *MockMeterBandBuilder) Burst(burst uint32) openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// Burst indicates an expected call of Burst.
func (mr *MockMeterBandBuilderMockRecorder) Burst(burst any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Done mocks base method.
func (m *MockMeterBandBuilder) Done() openflow.Meter {
	_ = "STUB: not implemented"
	return *new(openflow.Meter)
}

// Done indicates an expected call of Done.
func (mr *MockMeterBandBuilderMockRecorder) Done() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Experimenter mocks base method.
func (m *MockMeterBandBuilder) Experimenter(experimenter uint32) openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// Experimenter indicates an expected call of Experimenter.
func (mr *MockMeterBandBuilderMockRecorder) Experimenter(experimenter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MeterType mocks base method.
func (m *MockMeterBandBuilder) MeterType(meterType ofctrl.MeterType) openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// MeterType indicates an expected call of MeterType.
func (mr *MockMeterBandBuilderMockRecorder) MeterType(meterType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PrecLevel mocks base method.
func (m *MockMeterBandBuilder) PrecLevel(precLevel uint8) openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// PrecLevel indicates an expected call of PrecLevel.
func (mr *MockMeterBandBuilderMockRecorder) PrecLevel(precLevel any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Rate mocks base method.
func (m *MockMeterBandBuilder) Rate(rate uint32) openflow.MeterBandBuilder {
	_ = "STUB: not implemented"
	return *new(openflow.MeterBandBuilder)
}

// Rate indicates an expected call of Rate.
func (mr *MockMeterBandBuilderMockRecorder) Rate(rate any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
