// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
)

type StatsV1alpha1Interface interface {
	RESTClient() rest.Interface
	AntreaClusterNetworkPolicyStatsGetter
	AntreaNetworkPolicyStatsGetter
	MulticastGroupsGetter
	NetworkPolicyStatsGetter
	NodeLatencyStatsGetter
}

// StatsV1alpha1Client is used to interact with features provided by the stats.antrea.io group.
type StatsV1alpha1Client struct {
	restClient rest.Interface
}

func (c *StatsV1alpha1Client) AntreaClusterNetworkPolicyStats() AntreaClusterNetworkPolicyStatsInterface {
	_ = "STUB: not implemented"
	return *new(AntreaClusterNetworkPolicyStatsInterface)
}

func (c *StatsV1alpha1Client) AntreaNetworkPolicyStats(namespace string) AntreaNetworkPolicyStatsInterface {
	_ = "STUB: not implemented"
	return *new(AntreaNetworkPolicyStatsInterface)
}

func (c *StatsV1alpha1Client) MulticastGroups() MulticastGroupInterface {
	_ = "STUB: not implemented"
	return *new(MulticastGroupInterface)
}

func (c *StatsV1alpha1Client) NetworkPolicyStats(namespace string) NetworkPolicyStatsInterface {
	_ = "STUB: not implemented"
	return *new(NetworkPolicyStatsInterface)
}

func (c *StatsV1alpha1Client) NodeLatencyStats() NodeLatencyStatsInterface {
	_ = "STUB: not implemented"
	return *new(NodeLatencyStatsInterface)
}

// NewForConfig creates a new StatsV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*StatsV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new StatsV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*StatsV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new StatsV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *StatsV1alpha1Client { _ = "STUB: not implemented"; return nil }

// New creates a new StatsV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *StatsV1alpha1Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) { _ = "STUB: not implemented"; return }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *StatsV1alpha1Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
