// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
)

type ControlplaneV1beta2Interface interface {
	RESTClient() rest.Interface
	AddressGroupsGetter
	AppliedToGroupsGetter
	ClusterGroupMembersGetter
	EgressGroupsGetter
	GroupAssociationsGetter
	GroupMembersGetter
	IPGroupAssociationsGetter
	NetworkPoliciesGetter
	NetworkPolicyEvaluationsGetter
	NodeStatsSummariesGetter
	SupportBundleCollectionsGetter
}

// ControlplaneV1beta2Client is used to interact with features provided by the controlplane.antrea.io group.
type ControlplaneV1beta2Client struct {
	restClient rest.Interface
}

func (c *ControlplaneV1beta2Client) AddressGroups() AddressGroupInterface {
	_ = "STUB: not implemented"
	return *new(AddressGroupInterface)
}

func (c *ControlplaneV1beta2Client) AppliedToGroups() AppliedToGroupInterface {
	_ = "STUB: not implemented"
	return *new(AppliedToGroupInterface)
}

func (c *ControlplaneV1beta2Client) ClusterGroupMembers() ClusterGroupMembersInterface {
	_ = "STUB: not implemented"
	return *new(ClusterGroupMembersInterface)
}

func (c *ControlplaneV1beta2Client) EgressGroups() EgressGroupInterface {
	_ = "STUB: not implemented"
	return *new(EgressGroupInterface)
}

func (c *ControlplaneV1beta2Client) GroupAssociations(namespace string) GroupAssociationInterface {
	_ = "STUB: not implemented"
	return *new(GroupAssociationInterface)
}

func (c *ControlplaneV1beta2Client) GroupMembers(namespace string) GroupMembersInterface {
	_ = "STUB: not implemented"
	return *new(GroupMembersInterface)
}

func (c *ControlplaneV1beta2Client) IPGroupAssociations() IPGroupAssociationInterface {
	_ = "STUB: not implemented"
	return *new(IPGroupAssociationInterface)
}

func (c *ControlplaneV1beta2Client) NetworkPolicies() NetworkPolicyInterface {
	_ = "STUB: not implemented"
	return *new(NetworkPolicyInterface)
}

func (c *ControlplaneV1beta2Client) NetworkPolicyEvaluations() NetworkPolicyEvaluationInterface {
	_ = "STUB: not implemented"
	return *new(NetworkPolicyEvaluationInterface)
}

func (c *ControlplaneV1beta2Client) NodeStatsSummaries() NodeStatsSummaryInterface {
	_ = "STUB: not implemented"
	return *new(NodeStatsSummaryInterface)
}

func (c *ControlplaneV1beta2Client) SupportBundleCollections() SupportBundleCollectionInterface {
	_ = "STUB: not implemented"
	return *new(SupportBundleCollectionInterface)
}

// NewForConfig creates a new ControlplaneV1beta2Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ControlplaneV1beta2Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new ControlplaneV1beta2Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ControlplaneV1beta2Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new ControlplaneV1beta2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ControlplaneV1beta2Client {
	_ = "STUB: not implemented"
	return nil
}

// New creates a new ControlplaneV1beta2Client for the given RESTClient.
func New(c rest.Interface) *ControlplaneV1beta2Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) { _ = "STUB: not implemented"; return }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ControlplaneV1beta2Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
