// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/flowaggregator/exporter (interfaces: Runner)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/flowaggregator/exporter/testing/mock_exporter.go -package testing antrea.io/antrea/v2/pkg/flowaggregator/exporter Runner
//

// Package testing is a generated GoMock package.
package testing

import (
	context "context"

	v1alpha1 "antrea.io/antrea/v2/pkg/apis/flow/v1alpha1"
	ringbuffer "antrea.io/antrea/v2/pkg/flowaggregator/ringbuffer"
	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	_ = "STUB: not implemented"

	// Run mocks base method.
	return nil
}

func (m *MockRunner) Run(ctx context.Context, buf ringbuffer.BroadcastBuffer[*v1alpha1.Flow]) {
	_ = "STUB: not implemented"
	return
}

// Run indicates an expected call of Run.
func (mr *MockRunnerMockRecorder) Run(ctx, buf any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
