// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: pkg/apis/flow/v1alpha1/service.proto

package v1alpha1

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowExportService_Export_FullMethodName = "/antrea_io.antrea.pkg.apis.flow.v1alpha1.FlowExportService/Export"
)

// FlowExportServiceClient is the client API for FlowExportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowExportServiceClient interface {
	Export(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExportRequest, ExportResponse], error)
}

type flowExportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowExportServiceClient(cc grpc.ClientConnInterface) FlowExportServiceClient {
	_ = "STUB: not implemented"
	return *new(FlowExportServiceClient)
}

func (c *flowExportServiceClient) Export(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExportRequest, ExportResponse], error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowExportService_ExportClient = grpc.ClientStreamingClient[ExportRequest, ExportResponse]

// FlowExportServiceServer is the server API for FlowExportService service.
// All implementations must embed UnimplementedFlowExportServiceServer
// for forward compatibility.
type FlowExportServiceServer interface {
	Export(grpc.ClientStreamingServer[ExportRequest, ExportResponse]) error
	mustEmbedUnimplementedFlowExportServiceServer()
}

// UnimplementedFlowExportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowExportServiceServer struct{}

func (UnimplementedFlowExportServiceServer) Export(grpc.ClientStreamingServer[ExportRequest, ExportResponse]) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedFlowExportServiceServer) mustEmbedUnimplementedFlowExportServiceServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedFlowExportServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"
	return

	// UnsafeFlowExportServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to FlowExportServiceServer will
	// result in compilation errors.
}

type UnsafeFlowExportServiceServer interface {
	mustEmbedUnimplementedFlowExportServiceServer()
}

func RegisterFlowExportServiceServer(s grpc.ServiceRegistrar, srv FlowExportServiceServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedFlowExportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _FlowExportService_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowExportService_ExportServer = grpc.ClientStreamingServer[ExportRequest, ExportResponse]

// FlowExportService_ServiceDesc is the grpc.ServiceDesc for FlowExportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowExportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antrea_io.antrea.pkg.apis.flow.v1alpha1.FlowExportService",
	HandlerType: (*FlowExportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _FlowExportService_Export_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apis/flow/v1alpha1/service.proto",
}
