// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: antrea.io/antrea/v2/pkg/apis/stats/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"
)

func (m *AntreaClusterNetworkPolicyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *AntreaClusterNetworkPolicyStatsList) Reset() { _ = "STUB: not implemented"; return }

func (m *AntreaNetworkPolicyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *AntreaNetworkPolicyStatsList) Reset() { _ = "STUB: not implemented"; return }

func (m *MulticastGroup) Reset() { _ = "STUB: not implemented"; return }

func (m *MulticastGroupList) Reset() { _ = "STUB: not implemented"; return }

func (m *NetworkPolicyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *NetworkPolicyStatsList) Reset() { _ = "STUB: not implemented"; return }

func (m *NodeLatencyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *NodeLatencyStatsList) Reset() { _ = "STUB: not implemented"; return }

func (m *PeerNodeLatencyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *PodReference) Reset() { _ = "STUB: not implemented"; return }

func (m *RuleTrafficStats) Reset() { _ = "STUB: not implemented"; return }

func (m *TargetIPLatencyStats) Reset() { _ = "STUB: not implemented"; return }

func (m *TrafficStats) Reset() { _ = "STUB: not implemented"; return }

func (m *AntreaClusterNetworkPolicyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AntreaClusterNetworkPolicyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaClusterNetworkPolicyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaClusterNetworkPolicyStatsList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AntreaClusterNetworkPolicyStatsList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaClusterNetworkPolicyStatsList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaNetworkPolicyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AntreaNetworkPolicyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaNetworkPolicyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaNetworkPolicyStatsList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AntreaNetworkPolicyStatsList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AntreaNetworkPolicyStatsList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MulticastGroup) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MulticastGroup) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MulticastGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MulticastGroupList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MulticastGroupList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MulticastGroupList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkPolicyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NetworkPolicyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkPolicyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkPolicyStatsList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NetworkPolicyStatsList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkPolicyStatsList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NodeLatencyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NodeLatencyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NodeLatencyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NodeLatencyStatsList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NodeLatencyStatsList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NodeLatencyStatsList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PeerNodeLatencyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PeerNodeLatencyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PeerNodeLatencyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PodReference) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PodReference) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PodReference) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTrafficStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTrafficStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTrafficStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TargetIPLatencyStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TargetIPLatencyStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TargetIPLatencyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TrafficStats) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TrafficStats) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TrafficStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *AntreaClusterNetworkPolicyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AntreaClusterNetworkPolicyStatsList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AntreaNetworkPolicyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AntreaNetworkPolicyStatsList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MulticastGroup) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MulticastGroupList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NetworkPolicyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NetworkPolicyStatsList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NodeLatencyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NodeLatencyStatsList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PeerNodeLatencyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PodReference) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTrafficStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TargetIPLatencyStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TrafficStats) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenerated(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenerated(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (this *AntreaClusterNetworkPolicyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *AntreaClusterNetworkPolicyStatsList) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (this *AntreaNetworkPolicyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *AntreaNetworkPolicyStatsList) String() string { _ = "STUB: not implemented"; return "" }

func (this *MulticastGroup) String() string { _ = "STUB: not implemented"; return "" }

func (this *MulticastGroupList) String() string { _ = "STUB: not implemented"; return "" }

func (this *NetworkPolicyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *NetworkPolicyStatsList) String() string { _ = "STUB: not implemented"; return "" }

func (this *NodeLatencyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *NodeLatencyStatsList) String() string { _ = "STUB: not implemented"; return "" }

func (this *PeerNodeLatencyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *PodReference) String() string { _ = "STUB: not implemented"; return "" }

func (this *RuleTrafficStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *TargetIPLatencyStats) String() string { _ = "STUB: not implemented"; return "" }

func (this *TrafficStats) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringGenerated(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *AntreaClusterNetworkPolicyStats) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AntreaClusterNetworkPolicyStatsList) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AntreaNetworkPolicyStats) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AntreaNetworkPolicyStatsList) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MulticastGroup) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MulticastGroupList) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NetworkPolicyStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NetworkPolicyStatsList) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *NodeLatencyStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NodeLatencyStatsList) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PeerNodeLatencyStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PodReference) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RuleTrafficStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TargetIPLatencyStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TrafficStats) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGenerated(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
